import { optionsFromStrings } from '@li/config/utils';

// cspell:disable
export const BankName = [
  'Andhra Pradesh Grameena Vikas Bank',
  'AU Small Finance Bank',
  'Axis Bank',
  'Bandhan Bank',
  'Bank of Baroda',
  'Bank of India',
  'Bank of Maharashtra',
  'Baroda Gujarat Gramin Bank',
  'Bharat Co-operative Bank (Mumbai) Limited',
  'BNP Paribas',
  'Canara Bank',
  'Central Bank of India',
  'Chhattisgarh Rajya Gramin Bank',
  'City Union Bank',
  'Cosmos Bank',
  'CSB Bank',
  'DBS Bank',
  'DCB Bank',
  'Dhanlaxmi Bank',
  'ESAF Small Finance Bank',
  'Federal Bank',
  'HDFC Bank',
  'Himachal Pradesh Gramin Bank',
  'HSBC Bank India',
  'ICICI Bank',
  'IDBI Bank',
  'IDFC First Bank',
  'Indian Bank',
  'Indian Overseas Bank',
  'IndusInd Bank',
  'Jammu & Kashmir Bank',
  'Jana Small Finance Bank',
  'Karnataka Bank',
  'Karnataka Gramin Bank',
  'Karnataka Vikas Grameena Bank',
  'Karur Vysya Bank',
  'Kerala State Co-operative Bank Limited',
  'Kotak Mahindra Bank',
  'Maharashtra Gramin Bank',
  'Punjab and Sind Bank',
  'Punjab National Bank',
  'RBL Bank',
  'South Indian Bank',
  'State Bank of India',
  'Tamilnad Mercantile Bank',
  'UCO Bank',
  'Ujjivan Small Finance Bank',
  'Union Bank of India',
  'Yes Bank',
] as const;
// cspell:enable

export const BankNameOptions = optionsFromStrings(BankName);
