import { optionsFromStrings } from '@li/config/utils';
import { SelectItemElement } from '@li/types/design';
import { AvailableCountryCode, availableCountryCode } from './Country';

//cspell:disable
export const CountryBanks: {
  [C in AvailableCountryCode]: string[];
} = {
  lk: [
    'Amana Bank',
    'Bank Of Ceylon',
    'Bank Of China',
    'Cargills Bank',
    'Citibank',
    'Commercial Bank Of Ceylon',
    'Deutsche Bank',
    'Dfcc Bank',
    'Habib Bank',
    'Hatton National Bank',
    'Indian Bank',
    'Indian Overseas Bank',
    'Mcb Bank',
    'National Development Bank',
    'Nations Trust Bank',
    'Pan Asia Bank',
    'Public Bank Berhad',
    'Sampath Bank',
    'Seylan Bank',
    'Standard Chartered Bank',
    'State Bank Of India',
    'Union Bank Of Colombo',
    "People's Bank",
  ],
  jo: [
    'Al-Rajhi Bank',
    'Arab Bank',
    'Arab Banking Corporation',
    'Arab Jordan Investment Bank',
    'Bank Al Etihad',
    'Bank Audi',
    'Bank Of Jordan',
    'Blink',
    'Cairo Amman Bank',
    'Capital Bank Of Jordan',
    'Central Bank Of Jordan',
    'Citibank',
    'Egyptian Arab Land Bank',
    'Housing Bank For Trade & Finance',
    'Ila',
    'Investbank',
    'Islamic International Arab Bank',
    'Jordan Ahli Bank',
    'Jordan Commercial Bank',
    'Jordan Islamic Bank',
    'Jordan Kuwait Bank',
    'National Bank Of Kuwait',
    'Rafidain Bank',
    'Reflect',
    'Safwa Islamic Bank',
    'Société Générale De Banque Jordanie',
    'Standard Chartered',
  ],
  th: [
    'Bangkok Bank',
    'Bank For Agriculture And Agricultural Co-Operatives (Baac)',
    'Bank Of Ayudhya',
    'Cimb Thai Bank',
    'Export-Import Bank Of Thailand',
    'Gh Bank',
    'Government Savings Bank',
    'Icbc Thai',
    'Islamic Bank Of Thailand',
    'Kasikornbank',
    'Kiatnakin Phatra Bank',
    'Krung Thai Bank',
    'Land & Houses Bank',
    'Siam Commercial Bank',
    'Standard Chartered Bank',
    'Thai Credit Bank',
    'Tisco Bank',
    'Tmbthanachart Bank',
    'United Overseas Bank ',
  ],
  bh: [
    'Ahli United Bank',
    'Al Bakra Bank Group',
    'Arab Banking Corporation',
    'Arcapita',
    'Bahrain Development Bank',
    'Bank Of Bahrain And Kuwait',
    'Gulf International Bank',
    'Investcorp.',
    'Ithmaar Bank',
    'National Bank Of Bahrain',
  ],
  bt: [
    'Bank Of Bhutan',
    'Bhutan Development Bank',
    'Bhutan National Bank',
    'Druk Kidu Digital Bank',
    'Druk Pnb Bank',
    'Royal Monetary Authority Of Bhutan',
    'Tashi Bank ',
  ],
  id: [
    'Bank Central Asia',
    'Bank Mandiri',
    'Bank Negara Indonesia',
    'Bank Rakyat Indonesia',
    'Bank Syariah Indonesia',
    'Bank Tabungan Negara',
    'Cimb Niaga',
    'Ocbc Nisp',
    'Panin Bank',
    'Permata Bank',
  ],
  my: [
    'Cimb Group Holdings',
    'Affin Bank',
    'Agrobank',
    'Al-Rajhi Malaysia',
    'Alliance Bank Malaysia Berhad',
    'Ambank',
    'American Express Bank (Malaysia) Berhad',
    'Bangkok Bank Berhad',
    'Bank Islam Malaysia',
    'Bank Muamalat Malaysia Berhad',
    'Bank Of America Malaysia Berhad',
    'Bank Of China (Malaysia) Berhad',
    'Bank Of Tokyo-Mitsubishi Ufj (Malaysia) Berhad',
    'Bank Rakyat',
    'Bank Simpanan Nasional (Bsn)',
    'Bnp Paribas Malaysia Berhad',
    'China Construction Bank (Malaysia) Berhad[2]',
    'Citibank Berhad (Sold To Uob Group Malaysia)',
    'Citibank Malaysia',
    'Co-Op Bank Pertama',
    'Deutsche Bank (Malaysia) Berhad',
    'Hong Leong Bank',
    'Hsbc Bank Malaysia Berhad',
    'Hsbc Bank Malaysia',
    'India International Bank (Malaysia) Berhad',
    'Industrial And Commercial Bank Of China (Malaysia) Berhad',
    'J.P. Morgan Chase Bank Berhad',
    'Mbsb Bank Berhad',
    'Mbsb Bank',
    'Mizuho Bank (Malaysia)',
    'Ocbc Bank (Malaysia) Berhad',
    'Ocbc Bank Malaysia',
    'Public Bank Berhad',
    'Rhb Bank',
    'Standard Chartered Bank Malaysia',
    'Sumitomo Mitsui Banking Corporation Malaysia Berhad',
    'The Bank Of Nova Scotia Berhad',
    'United Overseas Bank (Malaysia) Bhd.',
    'Uob Malaysia',
  ],
  mv: [
    'Bank Of Ceylon',
    'Bank Of Maldives',
    'Commercial Bank Of Maldives',
    'Habib Bank Limited',
    'Maldives Islamic Bank',
    'State Bank Of India',
    'The Hongkong And Shanghai Banking Corporation',
    'The Mauritius Commercial Bank (Maldives) Private Limited',
  ],
  np: [
    'Agriculture Development Bank',
    'Bank Of Asia Nepal',
    'Bank Of Kathmandu',
    'Century Commercial Bank',
    'Citizens Bank International Limited',
    'Civil Bank',
    'Commerz & Trust Bank',
    'Corporate Development Bank',
    'Everest Bank',
    'Excel Development Bank',
    'Garima Bikas Bank',
    'Global Bank',
    'Global Ime Bank Limited',
    'Grand Bank Nepal',
    'Green Development Bank',
    'Himalayan Bank',
    'Janata Bank',
    'Jyoti Bikas Bank',
    'Kamana Sewa Bikas Bank',
    'Karnali Development Bank',
    'Kist Bank',
    'Kumari Bank',
    'Laxmi Bank',
    'Laxmi Sunrise Bank',
    'Lumbini Bank',
    'Lumbini Bikas Bank',
    'Machhapuchhre Bank',
    'Mahalaxmi Development Bank',
    'Mega Bank Nepal',
    'Miteri Development Bank',
    'Muktinath Bikash Bank',
    'Nabil Bank',
    'Narayani Development Bank',
    'Nepal Bangladesh Bank',
    'Nepal Bank',
    'Nepal Credit & Commerce Bank',
    'Nepal Industrial And Commercial Bank',
    'Nepal Investment Bank',
    'Nepal Investment Mega Bank',
    'Nepal Sbi Bank',
    'Nic Asia Bank',
    'Nmb Bank',
    'Prabhu Bank',
    'Prime Commercial Bank',
    'Rastriya Banijya Bank',
    'Salapa Bikash Bank',
    'Sangrila Development Bank',
    'Sanima Bank',
    'Saptakoshi Development Bank',
    'Shine Resunga Development Bank',
    'Siddhartha Bank',
    'Sindhu Bikas Bank',
    'Standard Chartered Bank',
    'Sunrise Bank',
  ],
  qa: [
    'Qatar National Bank',
    'Ahlibank',
    'Arab Bank Qatar',
    'Bank Saderat Iran - Qatar',
    'Bnp Paribas Middle East Africa',
    'Commercial Bank Of Qatar',
    'Doha Bank',
    'Dukhan Bank1',
    'Hsbc Bank Middle East',
    'Mashreq Bank Qatar',
    'Masraf Al Rayan',
    'Qatar Development Bank',
    'Qatar International Islamic Bank',
    'Qatar Islamic Bank',
    'Standard Chartered Qatar',
    'United Bank Limited - Qatar',
  ],
  ph: [
    'Allbank, Inc.',
    '26. Malayan Savings Bank',
    'Bank Of Makati',
    'Bank One Savings Corporation',
    'Bataan Development Bank',
    'Bpi Direct Banko, Inc.',
    'Card Sme Bank, Inc.',
    'Century Savings Bank Corporation',
    'City Savings Bank',
    'Citystate Savings Bank',
    'Cordillera Savings Bank, Inc.',
    'Dumaguete City Development Bank, Inc.',
    'Equicom Savings Bank',
    'First Consolidated Bank, Inc.',
    'Hiyas Banking Corporation',
    'Hsbc Savings Bank Philippines Inc.',
    'Isla Bank ',
    'Legazpi Savings Bank',
    'Lemery Savings And Loan Bank, Inc.',
    'Life Savings Bank, Inc.',
    'Lolc Bank Philippines, Inc.',
    'Luzon Development Bank',
    'Makiling Development Bank Corporation',
    'Northpoint Development Bank, Inc.',
    'Overseas Filipino Bank',
    'Pacific Ace Savings Bank, Inc.',
    'Pampanga Development Bank',
    'Pen Bank, Inc. ',
    'Philippine Business Bank',
    'Philippine Savings Bank',
    'Philippine Star Development Bank, Inc.',
    'Producers Savings Bank Corporation',
    'Queen City Development Bank',
    'Quezon Coconut Bank, Inc. ',
    'Rizal Microbank, Inc.',
    'Sterling Bank Of Asia',
    'Sun Savings Bank, Inc.',
    'Ucpb Savings Bank ',
    'University Savings Bank, Inc.',
    'Wealth Development Bank Corporation',
    'Yuanta Savings Bank Philippines, Inc.',
  ],
  sg: [
    'Standard Chartered Singapore',
    'Bangkok Bank Public Company Limited',
    'Bank Of America, National Association',
    'Bank Of China Limited',
    'Bank Of East Asia Limited, The',
    'Bank Of India',
    'Bank Of Tokyo-Mitsubishi Ufj Limited, The',
    'Calyon',
    'Cimb Bank',
    'Citibank Singapore',
    'Hong Leong Bank Berhad',
    'Hongkong And Shanghai Banking Corporation Limited',
    'Indian Bank',
    'Indian Overseas Bank',
    'Jpmorgan Chase Bank, National Association',
    'Maybank Singapore Limited',
    'Ping An Bank',
    'Pt Bank Mandiri (Persero) Tbk.',
    'Pt Bank Negara Indonesia (Persero) Tbk.',
    'Rhb Bank Berhad',
    'Sumitomo Mitsui Banking Corporation',
    'Uco Bank',
  ],
  ae: [
    'National Bank Of Bahrain',
    'Agricultural Bank Of China Ltd.',
    'Al Ahli Bank Of Kuwait',
    'Al Khaliji',
    'American Express Bank',
    'Arab African International Bank',
    'Arab Bank',
    'Bank Alfalah Limited',
    'Bank Melli Iran',
    'Bank Of Baroda',
    'Bank Of China Limited',
    'Bank Saderat Iran',
    'Banque Banorient France',
    'Banque Misr',
    'Barclays Bank Plc',
    'Bnp Paribas',
    'Bok International Bank',
    'Citibank N. A.',
    'Credit Agricole',
    'Deutsche Bank Ag',
    'Doha Bank',
    'El Nilein Bank',
    'Gulf International Bank',
    'Habib Bank A.G Zurich',
    'Habib Bank Ltd.',
    'Hsbc Bank Middle East Limited',
    'Intesa Sanpaolo S.P.A',
    'Janata Bank Limited',
    'Keb Hana Bank',
    'Mcb Bank Limited',
    'National Bank Of Kuwait',
    'National Bank Of Oman',
    'Natwest Markets Plc',
    'Rafidain Bank',
    'Saudi National Bank',
    'Standard Chartered Bank',
    'United Bank Ltd.',
  ],
  vn: [
    'Gatehouse Bank Of United Kingdom',
    'Anz',
    'Bangkok Bank',
    'Bank Of America',
    'Bank Of China Closed',
    'Bank Of India',
    'Barclays',
    'Bnp Paribas',
    'Cimb Bank',
    'Citibank Vietnam',
    'Commonwealth Bank Of Australia',
    'Deutsche Bank',
    'Hfc Bank',
    'Hong Leong Bank',
    'Industrial Bank Of Korea',
    'Intesa Sanpaolo Exited Vietnam Market In 2018 And Sold Local Operations To Shinhan Bank (Korea)',
    'Jp Morgan Chase Bank',
    'Keb Hana Bank',
    'Maybank',
    'Mizuho Bank',
    'Natixis',
    'Public Bank Vietnam',
    'Scotiabank',
    'Shinhan Bank',
    'Siam Commercial Bank',
    'Standard Chartered Bank',
    'The Bank Of Tokyo-Mitsubishi Ufj',
    'United Overseas Bank',
    'Woori Bank',
  ],
  za: [
    'Bank Of Baroda',
    'Afrasia Bank Limited',
    'Banco Africano De Investimentos',
    'Banco Bic',
    'Banco Bpi Sa',
    'Banco Espirito Santo E Comercial De Lisboa',
    'Banco Santander Totta S.A.',
    'Bank Leumi Le-Israel Bm',
    'Bank Of America',
    'Bank Of China',
    'Bank Of Cyprus Group',
    'Bank Of India',
    'Bank Of Taiwan',
    'Barclays Bank Plc',
    'Barclays Private Clients International Limited',
    'Bnp Paribas',
    'Calyon Corporate And Investment Bank',
    'China Construction Bank Corporation',
    'Citibank N.A.',
    'Colorado Bank',
    'Commerzbank Ag Johannesburg',
    'Credit Suisse Ag',
    'Deutsche Bank Ag',
    'Ecobank',
    'Export-Import Bank Of India',
    'Fairbairn Private Bank (Isle Of Man) Limited',
    'Fairbairn Private Bank (Jersey) Limited',
    'First Bank Of Nigeria',
    'First City Monument Bank Plc',
    'Hellenic Bank Public Company Limited',
    'Hongkong And Shanghai Banking Corporation',
    'Hsbc Bank International Limited',
    'Icici Bank Limited',
    'Industrial And Commercial Bank Of China',
    'Jpmorgan Chase Bank',
    'Kfw Ipex-Bank Gmbh',
    'Lloyds Tsb Offshore Limited',
    'Mauritius Commercial Bank Limited',
    'Millennium Bcp',
    'Mukuru Service',
    'National Bank Of Egypt',
    'Natixis',
    'Royal Bank Of Scotland International Limited',
    'Société Générale',
    'Société Générale',
    'Standard Chartered Bank',
    'State Bank Of India',
    'Sumitomo Mitsui Banking Corporation',
    'The Bank Of New York Mellon',
    'The Bank Of Tokyo-Mitsubishi Ufj Limited',
    'The Export-Import Bank Of China',
    'The Mizuho Bank Limited',
    'The Royal Bank Of Scotland N.V.',
    'Ubs Ag',
    'Unicredit Bank Ag',
    'Union Bank Of Nigeria Plc',
    'Wells Fargo Bank',
    'Zenith Bank Plc',
  ],
  in: [
    'Andhra Pradesh Grameena Vikas Bank',
    'AU Small Finance Bank',
    'Axis Bank',
    'Bandhan Bank',
    'Bank of Baroda',
    'Bank of India',
    'Bank of Maharashtra',
    'Baroda Gujarat Gramin Bank',
    'Bharat Co-operative Bank (Mumbai) Limited',
    'BNP Paribas',
    'Canara Bank',
    'Central Bank of India',
    'Chhattisgarh Rajya Gramin Bank',
    'City Union Bank',
    'Cosmos Bank',
    'CSB Bank',
    'DBS Bank',
    'DCB Bank',
    'Dhanlaxmi Bank',
    'ESAF Small Finance Bank',
    'Federal Bank',
    'HDFC Bank',
    'Himachal Pradesh Gramin Bank',
    'HSBC Bank India',
    'ICICI Bank',
    'IDBI Bank',
    'IDFC First Bank',
    'Indian Bank',
    'Indian Overseas Bank',
    'IndusInd Bank',
    'Jammu & Kashmir Bank',
    'Jana Small Finance Bank',
    'Karnataka Bank',
    'Karnataka Gramin Bank',
    'Karnataka Vikas Grameena Bank',
    'Karur Vysya Bank',
    'Kerala State Co-operative Bank Limited',
    'Kotak Mahindra Bank',
    'Maharashtra Gramin Bank',
    'Punjab and Sind Bank',
    'Punjab National Bank',
    'RBL Bank',
    'South Indian Bank',
    'State Bank of India',
    'Tamilnad Mercantile Bank',
    'UCO Bank',
    'Ujjivan Small Finance Bank',
    'Union Bank of India',
    'Yes Bank',
  ],
  bd: [],
};

export const CountryBanksOptions = availableCountryCode.reduce(
  (a, c) => ({
    ...a,
    [c]: optionsFromStrings(CountryBanks[c]),
  }),
  {},
) as {
  [C in AvailableCountryCode]: SelectItemElement[];
};
