import { SelectItemElement } from '@li/types/design';
import { AvailableCountryCode } from './Country';

// cspell:disable
export const countryStates: { [k in AvailableCountryCode]: string[] } = {
  ae: ['Abu Dhabi', 'Al ain', 'Dubai'],
  bd: [
    'Barisal',
    'Chittagong',
    'Dhaka',
    'Khulna',
    'Mymensingh',
    'Rajshahi',
    'Rangpur',
    'Sylhet',
  ],
  bh: [
    'Capital Governorate',
    'Northern Governorate',
    'Muharraq Governorate',
    'Southern Governorate',
  ],
  bt: [
    'Bumthang',
    'Chukha',
    'Dagana',
    'Gasa',
    'Haa',
    'Lhuntse',
    'Mongar',
    'Paro',
    'Pemagatshel',
    'Punakha',
    'Samdrup Jongkhar',
    'Samtse',
    'Sarpang',
    'Thimphu',
    'Trashigang',
    'Trashi Yangtse',
    'Tsirang',
    'Wangdue Phodrang',
    'Zhemgang',
  ],
  id: [
    'Aceh',
    'Bali',
    'Bangka Belitung Islands',
    'Banten',
    'Bengkulu',
    'Central Java',
    'Central Kalimantan',
    'Central Sulawesi',
    'East Java',
    'East Kalimantan',
    'East Nusa Tenggara',
    'Gorontalo',
    'Jambi',
    'Lampung',
    'Maluku',
    'North Kalimantan',
    'North Maluku',
    'North Sulawesi',
    'North Sumatra',
    'Papua',
    'Riau',
    'Riau Islands',
    'Southeast Sulawesi',
    'South Kalimantan',
    'South Sulawesi',
    'South Sumatra',
    'West Java',
    'West Kalimantan',
    'West Nusa Tenggara',
    'West Papua',
    'West Sulawesi',
    'West Sumatra',
    'Special Region of Yogyakarta',
  ],
  in: [
    'Andaman and Nicobar Islands',
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chandigarh',
    'Chhattisgarh',
    'Dadra and Nagar Haveli and Daman and Diu',
    'Delhi',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu and Kashmir',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Ladakh',
    'Lakshadweep',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Puducherry',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
  ],
  jo: [
    '    Ajloun',
    'Amman',
    'Aqaba',
    'Balqa',
    'Irbid',
    'Jerash',
    'Karak',
    "Ma'an",
    'Madaba',
    'Mafraq',
    'Tafilah',
    'Zarqa',
  ],
  lk: [
    'Central Province',
    'Eastern Province',
    'North Central Province',
    'Northern Province',
    'North Western Province',
    'Sabaragamuwa Province',
    'Southern Province',
    'Uva Province',
    'Western Province',
  ],
  mv: [
    'Alif Alif',
    'Alif Dhaal',
    'Baa',
    'Dhaalu',
    'Faafu',
    'Gaafu Alif',
    'Gaafu Dhaalu',
    'Gnaviyani',
    'Haa Alif',
    'Haa Dhaalu',
    'Kaafu',
    'Laamu',
    'Lhaviyani',
    'Malé',
    'Meemu',
    'Noonu',
    'Raa',
    'Seenu',
    'Shaviyani',
    'Thaa',
    'Vaavu',
  ],
  my: [
    'Johor',
    'Kedah',
    'Kelantan',
    'Kuala Lumpur',
    'Labuan',
    'Malacca',
    'Negeri Sembilan',
    'Pahang',
    'Penang',
    'Perak',
    'Perlis',
    'Putrajaya',
    'Sabah',
    'Sarawak',
    'Selangor',
    'Terengganu',
  ],
  np: [
    'Province No. 1',
    'Province No. 2',
    'Bagmati Province',
    'Gandaki Province',
    'Lumbini Province',
    'Karnali Province',
    'Sudurpashchim Province',
  ],
  ph: [
    'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)',
    'Bicol Region (Region V)',
    'CALABARZON (Region IV-A)',
    'Caraga (Region XIII)',
    'Cagayan Valley (Region II)',
    'Central Luzon (Region III)',
    'Central Visayas (Region VII)',
    'Cordillera Administrative Region (CAR)',
    'Davao Region (Region XI)',
    'Eastern Visayas (Region VIII)',
    'Ilocos Region (Region I)',
    'MIMAROPA (Region IV-B)',
    'National Capital Region (NCR)',
    'Northern Mindanao (Region X)',
    'SOCCSKSARGEN (Region XII)',
    'Western Visayas (Region VI)',
    'Zamboanga Peninsula (Region IX)',
  ],
  qa: [
    'Al Daayen',
    'Al Khor',
    'Al Rayyan',
    'Al Shamal',
    'Al Wakrah',
    'Doha',
    'Umm Salal',
  ],
  sg: [
    'Central Singapore',
    'North East',
    'North West',
    'South East',
    'South West',
  ],
  th: [
    'Amnat Charoen',
    'Ang Thong',
    'Bangkok',
    'Bueng Kan',
    'Buri Ram',
    'Chachoengsao',
    'Chai Nat',
    'Chaiyaphum',
    'Chanthaburi',
    'Chiang Mai',
    'Chiang Rai',
    'Chon Buri',
    'Chumphon',
    'Kalasin',
    'Kamphaeng Phet',
    'Kanchanaburi',
    'Khon Kaen',
    'Krabi',
    'Lampang',
    'Lamphun',
    'Loei',
    'Lop Buri',
    'Mae Hong Son',
    'Maha Sarakham',
    'Mukdahan',
    'Nakhon Nayok',
    'Nakhon Pathom',
    'Nakhon Phanom',
    'Nakhon Ratchasima',
    'Nakhon Sawan',
    'Nakhon Si Thammarat',
    'Nan',
    'Narathiwat',
    'Nong Bua Lamphu',
    'Nong Khai',
    'Nonthaburi',
    'Pathum Thani',
    'Pattani',
    'Phang Nga',
    'Phatthalung',
    'Phayao',
    'Phetchabun',
    'Phetchaburi',
    'Phichit',
    'Phitsanulok',
    'Phra Nakhon Si Ayutthaya',
    'Phrae',
    'Phuket',
    'Prachin Buri',
    'Prachuap Khiri Khan',
    'Ranong',
    'Ratchaburi',
    'Rayong',
    'Roi Et',
    'Sa Kaeo',
    'Sakon Nakhon',
    'Samut Prakan',
    'Samut Sakhon',
    'Samut Songkhram',
    'Saraburi',
    'Satun',
    'Sing Buri',
    'Sisaket',
    'Songkhla',
    'Sukhothai',
    'Suphan Buri',
    'Surat Thani',
    'Surin',
    'Tak',
    'Trang',
    'Trat',
    'Ubon Ratchathani',
    'Udon Thani',
    'Uthai Thani',
    'Uttaradit',
    'Yala',
    'Yasothon',
  ],
  vn: [
    'An Giang',
    'Bà Rịa-Vũng Tàu',
    'Bắc Giang',
    'Bắc Kạn',
    'Bạc Liêu',
    'Bắc Ninh',
    'Bến Tre',
    'Bình Định',
    'Bình Dương',
    'Bình Phước',
    'Bình Thuận',
    'Cà Mau',
    'Cần Thơ',
    'Cao Bằng',
    'Đà Nẵng',
    'Đắk Lắk',
    'Đắk Nông',
    'Điện Biên',
    'Đồng Nai',
    'Đồng Tháp',
    'Gia Lai',
    'Hà Giang',
    'Hà Nam',
    'Hà Nội',
    'Hà Tĩnh',
    'Hải Dương',
    'Hải Phòng',
    'Hậu Giang',
    'Hòa Bình',
    'Hưng Yên',
    'Khánh Hòa',
    'Kiên Giang',
    'Kon Tum',
    'Lai Châu',
    'Lâm Đồng',
    'Lạng Sơn',
    'Lào Cai',
    'Long An',
    'Nam Định',
    'Nghệ An',
    'Ninh Bình',
    'Ninh Thuận',
    'Phú Thọ',
    'Phú Yên',
    'Quảng Bình',
    'Quảng Nam',
    'Quảng Ngãi',
    'Quảng Ninh',
    'Quảng Trị',
    'Sóc Trăng',
    'Sơn La',
    'Tây Ninh',
    'Thái Bình',
    'Thái Nguyên',
    'Thanh Hóa',
    'Thừa Thiên-Huế',
    'Tiền Giang',
    'Trà Vinh',
    'Tuyên Quang',
    'Vĩnh Long',
    'Vĩnh Phúc',
    'Yên Bái',
  ],
  // za: [
  //   'Eastern Cape',
  //   'Free State',
  //   'Gauteng',
  //   'KwaZulu-Natal',
  //   'Limpopo',
  //   'Mpumalanga',
  //   'Northern Cape',
  //   'North West',
  //   'Western Cape',
  // ],
};

export const CountryStateOptions: {
  [k in AvailableCountryCode]: SelectItemElement[];
} = Object.entries(countryStates).reduce(
  (a, [k, v]) => ({
    ...a,
    [k]: v.map((s) => ({ id: s, item: s })),
  }),
  {} as Record<AvailableCountryCode, SelectItemElement[]>,
);
