import { optionsFromStrings } from '@li/config/utils';

export const IndustrySector = [
  'Advertising & Marketing',
  'Aerospace',
  'Agriculture',
  'Auto ancillary',
  'Automobile',
  'Aviation',
  'Chemicals',
  'Commerce',
  'Computer',
  'Construction',
  'Cosmetics',
  'Education',
  'Electronics',
  'Energy',
  'Engineering',
  'Entertainment',
  'Finance',
  'Food & Beverages',
  'Garments',
  'Healthcare',
  'Hospitality',
  'Hotel',
  'Insurance',
  'Machinery & Equipment',
  'Manufacturing',
  'Metal & Wood',
  'Mining',
  'Pharmaceutics',
  'Power',
  'Services',
  'Software & Hardware',
  'Telecommunication',
  'Textile',
  'Tourism',
  'Transportation',
  'Others',
];

export const IndustrySectorOptions = optionsFromStrings(IndustrySector);
