import { SelectItemElement } from '@li/types/design';

export const MenuCategoriesId = [
  'accessories-audio',
  'accessories-camera',
  'accessories_general',
  'accessories-mobile',
  'accessories-musical',
  'agro-dry_fruits',
  'agro-fertilizer',
  'agro-fruits',
  'agro-grains',
  'agro-oils',
  'agro-seeds',
  'agro-spices',
  'agro-veggies',
  'apparel-kids',
  'apparel-men',
  'apparel-women',
  'apparel-fabric',
  'bathroom_accessories',
  'chemicals',
  'cleaners',
  'computer',
  'construction',
  'cosmetics-kids',
  'cosmetic-men',
  'cosmetic-women',
  'digital_signature',
  'electric_vehicle',
  'electrical',
  'electronics',
  'financial_services',
  'food_and_beverages',
  'footwear',
  'gardening',
  'handmade_emporium',
  'hardware',
  'heavy_tools',
  'herbal_nutrition',
  'home_decor',
  'kitchen_appliances',
  'kitchen_ware',
  'machinery',
  'packaging',
  'plastic_ware',
  'sports',
  'stationery',
  'textile_fabrics',
  'threads_and_laces',
  'toys',
] as const;

export type MenuCategoriesIdType = (typeof MenuCategoriesId)[number];

type SubCategory = {
  id: string;
  label: string;
};

type CategoryMenuItem = {
  id: MenuCategoriesIdType;
  name: string;
};

type CategoryMenuItemWithSub = {
  id: string;
  name: string;
  subItems: CategoryMenuItem[];
};

type CatCat = CategoryMenuItem | CategoryMenuItemWithSub;

export const MenuCategories: CatCat[] = [
  {
    id: 'accessories',
    name: 'Accessories',
    subItems: [
      {
        id: 'accessories-audio',
        name: 'Audio',
      },
      {
        id: 'accessories-camera',
        name: 'Camera',
      },
      {
        id: 'accessories_general',
        name: 'General',
      },
      {
        id: 'accessories-mobile',
        name: 'Mobile',
      },
      {
        id: 'accessories-musical',
        name: 'Musical',
      },
    ],
  },
  {
    id: 'agro',
    name: 'Agro',
    subItems: [
      {
        id: 'agro-dry_fruits',
        name: 'Dry Fruits',
      },
      {
        id: 'agro-fertilizer',
        name: 'Fertilizer',
      },
      {
        id: 'agro-fruits',
        name: 'Fruits',
      },
      {
        id: 'agro-grains',
        name: 'Grains',
      },
      {
        id: 'agro-oils',
        name: 'Oils',
      },
      {
        id: 'agro-seeds',
        name: 'Seeds',
      },
      {
        id: 'agro-spices',
        name: 'Spices',
      },
      {
        id: 'agro-veggies',
        name: 'Veggies',
      },
    ],
  },
  {
    id: 'apparel',
    name: 'Apparel',
    subItems: [
      {
        id: 'apparel-kids',
        name: 'Kids',
      },
      {
        id: 'apparel-men',
        name: 'Men',
      },
      {
        id: 'apparel-women',
        name: 'Women',
      },
      {
        id: 'apparel-fabric',
        name: 'Fabric',
      },
    ],
  },
  {
    id: 'bathroom_accessories',
    name: 'Bathroom Accessories',
  },
  {
    id: 'chemicals',
    name: 'Chemicals',
  },
  { id: 'cleaners', name: 'Cleaners' },
  {
    id: 'computer',
    name: 'Computer',
  },
  {
    id: 'construction',
    name: 'Construction',
  },
  {
    id: 'cosmetic',
    name: 'Cosmetic',
    subItems: [
      {
        id: 'cosmetics-kids',
        name: 'Kids',
      },
      {
        id: 'cosmetic-men',
        name: 'Men',
      },
      {
        id: 'cosmetic-women',
        name: 'Women',
      },
    ],
  },
  {
    id: 'digital_signature',
    name: 'Digital Signature',
  },
  { id: 'electric_vehicle', name: 'Electric Vehicle' },
  { id: 'electrical', name: 'Electrical' },
  {
    id: 'electronics',
    name: 'Electronics',
  },
  {
    id: 'financial_services',
    name: 'Financial services',
  },
  {
    id: 'food_and_beverages',
    name: 'Food And Beverages',
  },
  {
    id: 'footwear',
    name: 'Footwear',
  },
  {
    id: 'gardening',
    name: 'Gardening',
  },
  { id: 'handmade_emporium', name: 'Handmade Emporium' },
  {
    id: 'hardware',
    name: 'Hardware',
  },
  {
    id: 'heavy_tools',
    name: 'Heavy Tools',
  },
  {
    id: 'herbal_nutrition',
    name: 'Herbal Nutrition',
  },
  {
    id: 'home_decor',
    name: 'Home Decor',
  },
  {
    id: 'kitchen_appliances',
    name: 'Kitchen Appliances',
  },
  {
    id: 'kitchen_ware',
    name: 'Kitchen Ware',
  },
  {
    id: 'machinery',
    name: 'Machinery',
  },
  {
    id: 'packaging',
    name: 'Packaging',
  },
  { id: 'plastic_ware', name: 'Plastic Ware' },
  { id: 'sports', name: 'Sports' },
  {
    id: 'stationery',
    name: 'Stationery',
  },
  { id: 'textile_fabrics', name: 'Textile Fabrics' },
  {
    id: 'threads_and_laces',
    name: 'Threads And Laces',
  },
  {
    id: 'toys',
    name: 'Toys',
  },
];

export const MenuOptions: SelectItemElement<MenuCategoriesIdType>[] =
  MenuCategories.map((item: CatCat) =>
    'subItems' in item
      ? item.subItems.map((subItem) => ({
          id: subItem.id,
          item: `${item.name}-${subItem.name}`,
        }))
      : { id: item.id, item: item.name },
  ).flat();

export const SubCategories: { [k in MenuCategoriesIdType]: SubCategory[] } = {
  accessories_general: [
    { id: 'athletic', label: 'Athletic' },
    { id: 'bandana', label: 'Bandana' },
    { id: 'belly_support', label: 'Belly Support' },
    { id: 'belt', label: 'Belt' },
    { id: 'brooches', label: 'Brooches' },
    { id: 'caps', label: 'Caps' },
    { id: 'cufflinks', label: 'Cufflinks' },
    { id: 'gift_sets', label: 'Gift Sets' },
    { id: 'gloves', label: 'Gloves' },
    { id: 'hair_clips', label: 'Hair Clips' },
    { id: 'hairbands', label: 'Hairbands' },
    { id: 'handbags', label: 'Handbags' },
    { id: 'handkerchief', label: 'Handkerchief' },
    { id: 'hats', label: 'Hats' },
    { id: 'helmet', label: 'Helmet' },
    { id: 'lens_and_frames', label: 'Lens And Frames' },
    { id: 'mittens', label: 'Mittens' },
    { id: 'needles', label: 'Needles' },
    { id: 'perfumes', label: 'Perfumes' },
    { id: 'raincoats', label: 'Raincoats' },
    { id: 'shawls', label: 'Shawls' },
    { id: 'socks', label: 'Socks' },
    { id: 'stockings', label: 'Stockings' },
    { id: 'sunglasses', label: 'Sunglasses' },
    { id: 'tie', label: 'Tie' },
    { id: 'tights', label: 'Tights' },
    { id: 'umbrellas', label: 'Umbrellas' },
    { id: 'wallet', label: 'Wallet' },
  ],
  'accessories-audio': [
    { id: 'audio', label: 'Audio' },
    { id: 'bluetooth_speakers', label: 'Bluetooth Speakers' },
    { id: 'headphones_with_mic', label: 'Headphones With Mic' },
    { id: 'headsets', label: 'Headsets' },
    { id: 'home_theatre', label: 'Home Theatre' },
    { id: 'multimedia_speakers', label: 'Multimedia Speakers' },
    {
      id: 'noise_cancelling_headphones',
      label: 'Noise Cancelling Headphones',
    },
    { id: 'soundbars', label: 'Soundbars' },
    { id: 'speakers', label: 'Speakers' },
    { id: 'sports_headphones', label: 'Sports Headphones' },
  ],
  'accessories-camera': [
    { id: '360_degree_cameras', label: '360 Degree Cameras' },
    { id: 'action_cameras', label: 'Action Cameras' },
    { id: 'batteries', label: 'Batteries' },
    { id: 'camcorders', label: 'Camcorders' },
    { id: 'camera_bags', label: 'Camera Bags' },
    { id: 'camera_cases', label: 'Camera Cases' },
    { id: 'camera_lenses', label: 'Camera Lenses' },
    { id: 'digital_slrs', label: 'Digital Slrs' },
    { id: 'flash_accessories', label: 'Flash Accessories' },
    { id: 'mirrorless_cameras', label: 'Mirrorless Cameras' },
    { id: 'photo_studio_lighting', label: 'Photo Studio/Lighting' },
    { id: 'point_and_shoot', label: 'Point And Shoot' },
    { id: 'projectors', label: 'Projectors' },
    { id: 'security_cameras', label: 'Security Cameras' },
    { id: 'spy_cameras', label: 'Spy Cameras' },
    { id: 'tripods_monopods', label: 'Tripods/Monopods' },
  ],
  'accessories-mobile': [
    { id: 'battery', label: 'Battery' },
    { id: 'charger', label: 'Charger' },
    { id: 'charging_wire', label: 'Charging Wire' },
    { id: 'internal_hdd', label: 'Internal Hdd' },
    { id: 'lens_kits', label: 'Lens Kits' },
    { id: 'mobile_case', label: 'Mobile Case' },
    { id: 'mounts_stands', label: 'Mounts/Stands' },
    { id: 'pen_drives', label: 'Pen Drives' },
    { id: 'power_bank', label: 'Power Bank' },
    { id: 'screen_guard', label: 'Screen Guard' },
    { id: 'selfie_sticks', label: 'Selfie Sticks' },
    { id: 'skin_stickers', label: 'Skin Stickers' },
    { id: 'smartphones', label: 'Smartphones' },
    { id: 'ssd_card', label: 'Ssd Card' },
    { id: 'tablets', label: 'Tablets' },
  ],
  'accessories-musical': [
    { id: 'audio_interfaces', label: 'Audio Interfaces' },
    { id: 'cables_leads', label: 'Cables & Leads' },
    { id: 'dj_controllers', label: 'Dj Controllers' },
    { id: 'drum_accessories', label: 'Drum Accessories' },
    { id: 'drums_percussions', label: 'Drums & Percussions' },
    { id: 'guitars', label: 'Guitars' },
    { id: 'indian_instruments', label: 'Indian Instruments' },
    { id: 'karaoke', label: 'Karaoke' },
    { id: 'keyboards_synthesizers', label: 'Keyboards/Synthesizers' },
    { id: 'microphones', label: 'Microphones' },
    { id: 'piano_accessories', label: 'Piano Accessories' },
    { id: 'string_accessories', label: 'String Accessories' },
    { id: 'studio_accessories', label: 'Studio Accessories' },
    { id: 'wind_instruments', label: 'Wind Instruments' },
  ],
  'agro-dry_fruits': [
    { id: 'almonds', label: 'Almonds' },
    { id: 'apricot', label: 'Apricot' },
    { id: 'brazil_nuts', label: 'Brazil Nuts' },
    { id: 'cashews', label: 'Cashews' },
    { id: 'coconut', label: 'Coconut' },
    { id: 'dry_dates', label: 'Dry Dates' },
    { id: 'dry_corn', label: 'Dry Corn' },
    { id: 'dry_fig', label: 'Dry Fig' },
    { id: 'flax_seeds', label: 'Flax Seeds' },
    { id: 'hazelnuts', label: 'Hazelnuts' },
    { id: 'macadamia', label: 'Macadamia' },
    { id: 'peanuts', label: 'Peanuts' },
    { id: 'pecans', label: 'Pecans' },
    { id: 'pine_nuts', label: 'Pine Nuts' },
    { id: 'pistachio', label: 'Pistachio' },
    { id: 'pumpkin_seeds', label: 'Pumpkin Seeds' },
    { id: 'raisins_dry_grapes', label: 'Raisins/Dry Grapes' },
    { id: 'soy_nuts', label: 'Soy Nuts' },
    { id: 'strawberry', label: 'Strawberry' },
    { id: 'sunflower_seeds', label: 'Sunflower Seeds' },
    { id: 'walnuts', label: 'Walnuts' },
    { id: 'watermelon_seeds', label: 'Watermelon Seeds' },
    { id: 'saffron', label: 'Saffron' },
  ],
  'agro-fertilizer': [
    { id: 'bio_fertilizers', label: 'Bio Fertilizers' },
    { id: 'fertilizer', label: 'Fertilizer' },
    {
      id: 'micronutrient_fertilizers',
      label: 'Micronutrient Fertilizers',
    },
    { id: 'np_fertilizer', label: 'Np Fertilizer' },
    { id: 'nitrogen_fertilizers', label: 'Nitrogen Fertilizers' },
    {
      id: 'organic_fertilizers_and_manure',
      label: 'Organic Fertilizers And Manure',
    },
    { id: 'phosphate_fertilizers', label: 'Phosphate Fertilizers' },
    { id: 'plant_growth_promoters', label: 'Plant Growth Promoters' },
    { id: 'plant_growth_regulators', label: 'Plant Growth Regulators' },
    { id: 'soil_conditioner', label: 'Soil Conditioner' },
    { id: 'sulfur_fertilizers', label: 'Sulfur Fertilizers' },
    { id: 'urea', label: 'Urea' },
  ],
  'agro-fruits': [
    { id: 'banana', label: 'Banana' },
    { id: 'cherry', label: 'Cherry' },
    { id: 'coconut', label: 'Coconut' },
    { id: 'custard_apple', label: 'Custard Apple' },
    { id: 'dates', label: 'Dates' },
    { id: 'grapes', label: 'Grapes' },
    { id: 'guava', label: 'Guava' },
    { id: 'jackfruit', label: 'Jackfruit' },
    { id: 'kiwi', label: 'Kiwi' },
    { id: 'mango', label: 'Mango' },
    { id: 'musk_melon', label: 'Musk Melon' },
    { id: 'orange', label: 'Orange' },
    { id: 'papaya', label: 'Papaya' },
    { id: 'pear', label: 'Pear' },
    { id: 'pineapple', label: 'Pineapple' },
    { id: 'pomegranate', label: 'Pomegranate' },
    { id: 'sapota_chikoo', label: 'Sapota (Chikoo)' },
    { id: 'strawberry', label: 'Strawberry' },
    { id: 'sugarcane', label: 'Sugarcane' },
    { id: 'sweet_melon_mosambi', label: 'Sweet Melon (Mosambi)' },
    { id: 'watermelon', label: 'Watermelon' },
  ],
  'agro-grains': [
    { id: 'bajra', label: 'Bajra' },
    { id: 'beans', label: 'Beans' },
    { id: 'corn', label: 'Corn' },
    { id: 'cotton', label: 'Cotton' },
    { id: 'dal', label: 'Dal' },
    { id: 'jaggery', label: 'Jaggery' },
    { id: 'jawar', label: 'Jawar' },
    { id: 'oats', label: 'Oats' },
    { id: 'ragi', label: 'Ragi' },
    { id: 'rava', label: 'Rava' },
    { id: 'rice', label: 'Rice' },
    { id: 'soya', label: 'Soya' },
    { id: 'sugar', label: 'Sugar' },
    { id: 'wheat', label: 'Wheat' },
  ],
  'agro-oils': [
    { id: 'almond_oils', label: 'Almond Oils' },
    { id: 'blended_olive_oil', label: 'Blended Olive Oil' },
    { id: 'canned_olive_oil', label: 'Canned Olive Oil' },
    { id: 'cashew_nut_shell_liquid', label: 'Cashew Nut Shell Liquid' },
    { id: 'cashew_nut_shell_oil', label: 'Cashew Nut Shell Oil' },
    { id: 'coconut_cooking_oil', label: 'Coconut Cooking Oil' },
    { id: 'coconut_oil', label: 'Coconut Oil' },
    { id: 'cold_pressed_coconut_oil', label: 'Cold Pressed Coconut Oil' },
    { id: 'cold_pressed_peanut_oil', label: 'Cold Pressed Peanut Oil' },
    {
      id: 'cold_pressed_sunflower_oil',
      label: 'Cold Pressed Sunflower Oil',
    },
    { id: 'cottonseed_oil', label: 'Cottonseed Oil' },
    { id: 'crude_sunflower_oil', label: 'Crude Sunflower Oil' },
    { id: 'edible_oil', label: 'Edible Oil' },
    { id: 'extra_virgin_olive_oil', label: 'Extra Virgin Olive Oil' },
    { id: 'filtered_groundnut_oil', label: 'Filtered Groundnut Oil' },
    { id: 'fractionated_coconut_oil', label: 'Fractionated Coconut Oil' },
    { id: 'groundnut_oil', label: 'Groundnut Oil' },
    { id: 'hazelnut_oil', label: 'Hazelnut Oil' },
    { id: 'industrial_coconut_oil', label: 'Industrial Coconut Oil' },
    { id: 'mustard_oil', label: 'Mustard Oil' },
    { id: 'nut_oils', label: 'Nut Oils' },
    { id: 'olive_oil', label: 'Olive Oil' },
    { id: 'olive_pomace_oil', label: 'Olive Pomace Oil' },
    { id: 'onion_oleoresin', label: 'Onion Oleoresin' },
    { id: 'organic_coconut_oil', label: 'Organic Coconut Oil' },
    { id: 'palm_oil', label: 'Palm Oil' },
    { id: 'rectified_clove_leaf_oil', label: 'Rectified Clove Leaf Oil' },
    { id: 'refined_canola_oil', label: 'Refined Canola Oil' },
    { id: 'refined_coconut_oil', label: 'Refined Coconut Oil' },
    { id: 'refined_groundnut_oil', label: 'Refined Groundnut Oil' },
    { id: 'refined_oil', label: 'Refined Oil' },
    { id: 'refined_rapeseed_oil', label: 'Refined Rapeseed Oil' },
    { id: 'refined_sesame_oil', label: 'Refined Sesame Oil' },
    { id: 'refined_sunflower_oil', label: 'Refined Sunflower Oil' },
    { id: 'roasted_coconut_oil', label: 'Roasted Coconut Oil' },
    { id: 'sesame_oil', label: 'Sesame Oil' },
    { id: 'soybean_refined_oil', label: 'Soybean Refined Oil' },
    { id: 'sunflower_oil', label: 'Sunflower Oil' },
    { id: 'vegetable_oil', label: 'Vegetable Oil' },
    { id: 'virgin_coconut_oil', label: 'Virgin Coconut Oil' },
    { id: 'virgin_groundnut_oil', label: 'Virgin Groundnut Oil' },
    { id: 'virgin_sunflower_oil', label: 'Virgin Sunflower Oil' },
    {
      id: 'wood_pressed_groundnut_oil',
      label: 'Wood Pressed Groundnut Oil',
    },
  ],
  'agro-seeds': [
    { id: 'agriculture_seeds', label: 'Agriculture Seeds' },
    { id: 'bean_seeds', label: 'Bean Seeds' },
    { id: 'cotton_seeds', label: 'Cotton Seeds' },
    { id: 'edible_seeds', label: 'Edible Seeds' },
    { id: 'flower_seeds', label: 'Flower Seeds' },
    { id: 'fodder_seeds', label: 'Fodder Seeds' },
    { id: 'fruit_seeds', label: 'Fruit Seeds' },
    { id: 'grain_seed', label: 'Grain Seed' },
    { id: 'grass_seeds', label: 'Grass Seeds' },
    { id: 'herb_seeds', label: 'Herb Seeds' },
    { id: 'hybrid_seeds', label: 'Hybrid Seeds' },
    { id: 'jute_seeds', label: 'Jute Seeds' },
    { id: 'medicinal_plant_seeds', label: 'Medicinal Plant Seeds' },
    { id: 'mulberry_seeds', label: 'Mulberry Seeds' },
    { id: 'mustard_seeds', label: 'Mustard Seeds' },
    { id: 'oat_seeds', label: 'Oat Seeds' },
    { id: 'oil_seeds', label: 'Oil Seeds' },
    { id: 'organic_seed', label: 'Organic Seed' },
    { id: 'seed_spices', label: 'Seed Spices' },
    { id: 'sesame_seed', label: 'Sesame Seed' },
    { id: 'shrub_seeds', label: 'Shrub Seeds' },
    { id: 'tea_seeds', label: 'Tea Seeds' },
    { id: 'thyme_seeds', label: 'Thyme Seeds' },
    { id: 'tree_seeds', label: 'Tree Seeds' },
    { id: 'vegetable_seeds', label: 'Vegetable Seeds' },
  ],
  'agro-spices': [
    { id: 'asafoetida', label: 'Asafoetida' },
    { id: 'bay_leaf', label: 'Bay Leaf' },
    { id: 'black_pepper', label: 'Black Pepper' },
    { id: 'cardamon', label: 'Cardamon' },
    { id: 'cinnamon', label: 'Cinnamon' },
    { id: 'cloves', label: 'Cloves' },
    { id: 'cumin', label: 'Cumin' },
    { id: 'dry_coriander', label: 'Dry Coriander' },
    { id: 'fennel_seed', label: 'Fennel Seed' },
    { id: 'fenugreek_seeds', label: 'Fenugreek Seeds' },
    { id: 'ginger', label: 'Ginger' },
    { id: 'nutmeg', label: 'Nutmeg' },
    { id: 'red_chilli', label: 'Red Chilli' },
    { id: 'saffron', label: 'Saffron' },
    { id: 'sesame_seeds', label: 'Sesame Seeds' },
    { id: 'tamarind', label: 'Tamarind' },
    { id: 'turmeric', label: 'Turmeric' },
  ],
  'agro-veggies': [
    { id: 'avocado', label: 'Avocado' },
    { id: 'beans', label: 'Beans' },
    { id: 'broccoli', label: 'Broccoli' },
    { id: 'cabbage', label: 'Cabbage' },
    { id: 'carrots', label: 'Carrots' },
    { id: 'celery', label: 'Celery' },
    { id: 'corn', label: 'Corn' },
    { id: 'eggplant', label: 'Eggplant' },
    { id: 'garlic', label: 'Garlic' },
    { id: 'gourds', label: 'Gourds' },
    { id: 'leafy_greens', label: 'Leafy Greens' },
    { id: 'mushrooms', label: 'Mushrooms' },
    { id: 'onions', label: 'Onions' },
    { id: 'potatoes', label: 'Potatoes' },
    { id: 'peas', label: 'Peas' },
    { id: 'pepper', label: 'Pepper' },
    { id: 'raddish', label: 'Raddish' },
    { id: 'tomato', label: 'Tomato' },
    { id: 'yam', label: 'Yam' },
    { id: 'cauliflower', label: 'Cauliflower' },
    { id: 'cucumber', label: 'Cucumber' },
  ],
  'apparel-kids': [
    { id: 'blazers', label: 'Blazers' },
    { id: 'cargo', label: 'Cargo' },
    { id: 'dhoti', label: 'Dhoti' },
    { id: 'dresses', label: 'Dresses' },
    { id: 'girl_skirts', label: 'Girl Skirts' },
    { id: 'girl_tops', label: 'Girl Tops' },
    { id: 'girl_frocks', label: 'Girl Frocks' },
    { id: 'gowns', label: 'Gowns' },
    { id: 'jackets', label: 'Jackets' },
    { id: 'jeans', label: 'Jeans' },
    { id: 'jeggings', label: 'Jeggings' },
    { id: 'jerseys', label: 'Jerseys' },
    { id: 'jumpsuits', label: 'Jumpsuits' },
    { id: 'kurta', label: 'Kurta' },
    { id: 'leggings', label: 'Leggings' },
    { id: 'nightwear', label: 'Nightwear' },
    { id: 'pajamas', label: 'Pajamas' },
    { id: 'rompers', label: 'Rompers' },
    { id: 'salwar_suit', label: 'Salwar Suit' },
    { id: 'shorts', label: 'Shorts' },
    { id: 'shrugs', label: 'Shrugs' },
    { id: 'suits', label: 'Suits' },
    { id: 'sweat_shirts', label: 'Sweat Shirts' },
    { id: 'sweater', label: 'Sweater' },
    { id: 'swim_wear', label: 'Swim Wear' },
    { id: 'tank_top', label: 'Tank Top' },
    { id: 'thermals', label: 'Thermals' },
    { id: 'track_pant', label: 'Track Pant' },
    { id: 'track_suits', label: 'Track Suits' },
    { id: 't_shirts', label: 'T-Shirts' },
    { id: 'uniforms', label: 'Uniforms' },
  ],
  'apparel-men': [
    { id: 'bandhgala', label: 'Bandhgala' },
    { id: 'blazers', label: 'Blazers' },
    { id: 'boxers', label: 'Boxers' },
    { id: 'briefs', label: 'Briefs' },
    { id: 'cargos', label: 'Cargos' },
    { id: 'dhoti', label: 'Dhoti' },
    { id: 'dry_fits', label: 'Dry Fits' },
    { id: 'gym_wear', label: 'Gym Wear' },
    { id: 'hoodies', label: 'Hoodies' },
    { id: 'jackets', label: 'Jackets' },
    { id: 'jeans', label: 'Jeans' },
    { id: 'joggers', label: 'Joggers' },
    { id: 'kurta', label: 'Kurta' },
    { id: 'pajamas', label: 'Pajamas' },
    { id: 'sherwani', label: 'Sherwani' },
    { id: 'shirts', label: 'Shirts' },
    { id: 'shorts', label: 'Shorts' },
    { id: 'suits', label: 'Suits' },
    { id: 'sweaters', label: 'Sweaters' },
    { id: 'sweat_shirts', label: 'Sweat Shirts' },
    { id: 'swimwear', label: 'Swimwear' },
    { id: 'tank_top', label: 'Tank Top' },
    { id: 'thermals', label: 'Thermals' },
    { id: 'track_pant', label: 'Track Pant' },
    { id: 'trousers', label: 'Trousers' },
    { id: 'trunks', label: 'Trunks' },
    { id: 't_shirts', label: 'T-Shirts' },
    { id: 'uniforms', label: 'Uniforms' },
    { id: 'vests', label: 'Vests' },
  ],
  'apparel-women': [
    { id: 'blazers', label: 'Blazers' },
    { id: 'blouse', label: 'Blouse' },
    { id: 'bottoms', label: 'Bottoms' },
    { id: 'bra', label: 'Bra' },
    { id: 'brief', label: 'Brief' },
    { id: 'camisoles', label: 'Camisoles' },
    { id: 'capris', label: 'Capris' },
    { id: 'cargos', label: 'Cargos' },
    { id: 'churidar', label: 'Churidar' },
    { id: 'dresses', label: 'Dresses' },
    { id: 'dupattas', label: 'Dupattas' },
    { id: 'gym_wear', label: 'Gym Wear' },
    { id: 'hijab', label: 'Hijab' },
    { id: 'hoodies', label: 'Hoodies' },
    { id: 'jackets', label: 'Jackets' },
    { id: 'jeans', label: 'Jeans' },
    { id: 'jeggings', label: 'Jeggings' },
    { id: 'joggers', label: 'Joggers' },
    { id: 'jumpsuits', label: 'Jumpsuits' },
    { id: 'kurtis', label: 'Kurtis' },
    { id: 'leggings', label: 'Leggings' },
    { id: 'lehenga_cholis', label: 'Lehenga Cholis' },
    { id: 'lingeries', label: 'Lingeries' },
    { id: 'peticoat', label: 'Peticoat' },
    { id: 'sarees', label: 'Sarees' },
    { id: 'shape_wear', label: 'Shape Wear' },
    { id: 'shawls', label: 'Shawls' },
    { id: 'shirts', label: 'Shirts' },
    { id: 'shorts', label: 'Shorts' },
    { id: 'shrugs', label: 'Shrugs' },
    { id: 'skirts', label: 'Skirts' },
    { id: 'skirts_palazzos', label: 'Skirts/Palazzos' },
    { id: 'sleepwear', label: 'Sleepwear' },
    { id: 'sweaters', label: 'Sweaters' },
    { id: 'sweatshirts', label: 'Sweatshirts' },
    { id: 'swimwear', label: 'Swimwear' },
    { id: 'thermals', label: 'Thermals' },
    { id: 'tops', label: 'Tops' },
    { id: 'track_pant', label: 'Track Pant' },
    { id: 'track_suits', label: 'Track Suits' },
    { id: 'trousers', label: 'Trousers' },
    { id: 't_shirts', label: 'T-Shirts' },
    { id: 't_shirts_tanks', label: 'T-Shirts/Tanks' },
    { id: 'uniforms', label: 'Uniforms' },
  ],
  'apparel-fabric': [
    { id: 'bleached', label: 'Bleached' },
    { id: 'blended', label: 'Blended' },
    { id: 'brasso', label: 'Brasso' },
    { id: 'cotton', label: 'Cotton' },
    { id: 'ethnic', label: 'Ethnic' },
    { id: 'handmade', label: 'Handmade' },
    { id: 'jute', label: 'Jute' },
    { id: 'knitted', label: 'Knitted' },
    { id: 'linen', label: 'Linen' },
    { id: 'nano', label: 'Nano' },
    { id: 'polycotton', label: 'Polycotton' },
    { id: 'polyster', label: 'Polyster' },
    { id: 'printed', label: 'Printed' },
    { id: 'ramie', label: 'Ramie' },
    { id: 'satin', label: 'Satin' },
    { id: 'silk', label: 'Silk' },
    { id: 'soft', label: 'Soft' },
    { id: 'sparkle', label: 'Sparkle' },
    { id: 'suiting', label: 'Suiting' },
    { id: 'viscose', label: 'Viscose' },
    { id: 'woolen', label: 'Woolen' },
    { id: 'yarns', label: 'Yarns' },
  ],
  bathroom_accessories: [
    { id: 'abs_bath_accessories', label: 'Abs Bath Accessories' },
    {
      id: 'acrylic_bathroom_accessories',
      label: 'Acrylic Bathroom Accessories',
    },
    { id: 'bath_headrest', label: 'Bath Headrest' },
    { id: 'bath_kit', label: 'Bath Kit' },
    { id: 'bath_set', label: 'Bath Set' },
    { id: 'bathroom_cabinet_mirrors', label: 'Bathroom Cabinet Mirrors' },
    { id: 'bathroom_grab_bar', label: 'Bathroom Grab Bar' },
    { id: 'bathroom_set', label: 'Bathroom Set' },
    { id: 'bathroom_tray', label: 'Bathroom Tray' },
    { id: 'bathtub_accessories', label: 'Bathtub Accessories' },
    { id: 'bath_ware', label: 'Bath Ware' },
    { id: 'body_dryer', label: 'Body Dryer' },
    { id: 'brass_bathroom_accessories', label: 'Brass Bathroom Accessories' },
    { id: 'ceramic_bathroom_set', label: 'Ceramic Bathroom Set' },
    { id: 'electric_hand_dryer', label: 'Electric Hand Dryer' },
    { id: 'grab_bars', label: 'Grab Bars' },
    { id: 'grab_rail', label: 'Grab Rail' },
    {
      id: 'marble_bathroom_accessories',
      label: 'Marble Bathroom Accessories',
    },
    { id: 'mirror_defogger', label: 'Mirror Defogger' },
    { id: 'paper_dispenser', label: 'Paper Dispenser' },
    { id: 'perfume_holder', label: 'Perfume Holder' },
    { id: 'plastic_bath_accessories', label: 'Plastic Bath Accessories' },
    { id: 'robe_hook', label: 'Robe Hook' },
    { id: 'soap_dishes', label: 'Soap Dishes' },
    {
      id: 'stainless_steel_bathroom_accessories',
      label: 'Stainless Steel Bathroom Accessories',
    },
    { id: 'tissue_holder', label: 'Tissue Holder' },
    { id: 'toothbrush_holder', label: 'Toothbrush Holder' },
    { id: 'toothpaste_dispenser', label: 'Toothpaste Dispenser' },
    { id: 'towel_holder', label: 'Towel Holder' },
    { id: 'towel_warmer', label: 'Towel Warmer' },
  ],
  chemicals: [
    {
      id: 'adhesives_glue_and_sealants',
      label: 'Adhesives, Glue And Sealants',
    },
    { id: 'agro_chemicals', label: 'Agro Chemicals' },
    { id: 'bio_chemicals', label: 'Bio Chemicals' },
    { id: 'bleaching_powder', label: 'Bleaching Powder' },
    {
      id: 'chemical_reagents_catalysts',
      label: 'Chemical Reagents & Catalysts',
    },
    { id: 'descaling_chemical', label: 'Descaling Chemical' },
    { id: 'disinfectant_chemicals', label: 'Disinfectant Chemicals' },
    { id: 'dyes_color_additives', label: 'Dyes & Color Additives' },
    {
      id: 'fertilizers_and_soil_additives',
      label: 'Fertilizers And Soil Additives',
    },
    { id: 'flavours_aromatics', label: 'Flavours & Aromatics' },
    { id: 'floor_chemicals', label: 'Floor Chemicals' },
    { id: 'food_chemicals', label: 'Food Chemicals' },
    { id: 'grease_cleansing_chemicals', label: 'Grease Cleansing Chemicals' },
    {
      id: 'industrial_cleaning_chemicals',
      label: 'Industrial Cleaning Chemicals',
    },
    {
      id: 'insecticides_and_pesticides',
      label: 'Insecticides And Pesticides',
    },
    {
      id: 'natural_and_synthetic_resins',
      label: 'Natural And Synthetic Resins',
    },
    {
      id: 'organic_and_inorganic_solvents',
      label: 'Organic And Inorganic Solvents',
    },
    {
      id: 'pet_granules_plastic_raw_material',
      label: 'Pet Granules & Plastic Raw Material',
    },
    {
      id: 'petroleum_and_petrochemical_product',
      label: 'Petroleum And Petrochemical Products',
    },
    { id: 'speciality_chemicals', label: 'Speciality Chemicals' },
    {
      id: 'surface_treatment_chemicals',
      label: 'Surface Treatment Chemicals',
    },
    {
      id: 'textile_dyeing_finishing_chemical',
      label: 'Textile, Dyeing & Finishing Chemical',
    },
    { id: 'tile_cleaner', label: 'Tile Cleaner' },
    { id: 'toluene', label: 'Toluene' },
  ],
  computer: [
    { id: 'desktop', label: 'Desktop' },
    { id: 'hdmi_cables', label: 'Hdmi Cables' },
    { id: 'ink_toners', label: 'Ink & Toners' },
    { id: 'ink_tank_printers', label: 'Ink Tank Printers' },
    { id: 'ink_jet_printers', label: 'Ink-jet Printers' },
    { id: 'keyboard', label: 'Keyboard' },
    { id: 'laptop', label: 'Laptop' },
    { id: 'laser_printers', label: 'Laser Printers' },
    { id: 'monitor', label: 'Monitor' },
    { id: 'mouse', label: 'Mouse' },
    { id: 'printers', label: 'Printers' },
    { id: 'vga_cable', label: 'Vga Cable' },
  ],
  construction: [
    {
      id: 'acoustic_window_foam_enclosures',
      label: 'Acoustic Window, Foam & Enclosures',
    },
    {
      id: 'aluminum_brass_bronze_pipes',
      label: 'Aluminum, Brass, Bronze Pipes',
    },
    {
      id: 'architectural_civil_engineering',
      label: 'Architectural & Civil Engineering',
    },
    {
      id: 'beams_purlins_frames_and_girders',
      label: 'Beams, Purlins, Frames And Girders',
    },
    {
      id: 'brackets_holder_hardware_fittings',
      label: 'Brackets, Holder & Hardware Fittings',
    },
    {
      id: 'bricks_construction_aggregates',
      label: 'Bricks & Construction Aggregates',
    },
    {
      id: 'building_construction_machines',
      label: 'Building & Construction Machines',
    },
    {
      id: 'building_real_estate_developers',
      label: 'Building & Real Estate Developers',
    },
    {
      id: 'building_panels_cladding_materials',
      label: 'Building Panels & Cladding Materials',
    },
    { id: 'carts_dollies_trolleys', label: 'Carts, Dollies & Trolleys' },
    { id: 'cement_and_concrete', label: 'Cement And Concrete' },
    {
      id: 'clamps_and_clamping_equipment',
      label: 'Clamps And Clamping Equipment',
    },
    {
      id: 'cobbles_pebbles_pavings',
      label: 'Cobbles, Pebbles & Pavings',
    },
    {
      id: 'cranes_forklift_lifting_machines',
      label: 'Cranes, Forklift & Lifting Machines',
    },
    {
      id: 'door_skins_panels_profile',
      label: 'Door Skins, Panels & Profile',
    },
    {
      id: 'door_window_handles_knockers',
      label: 'Door, Window Handles & Knockers',
    },
    { id: 'doors_and_windows', label: 'Doors And Windows' },
    { id: 'elevators_escalators', label: 'Elevators & Escalators' },
    {
      id: 'excavator_and_earth_moving_machinery',
      label: 'Excavator And Earth Moving Machinery',
    },
    {
      id: 'frp_lining_pu_powder_coatings',
      label: 'Frp Lining, Pu & Powder Coatings',
    },
    {
      id: 'fountains_water_features',
      label: 'Fountains & Water Features',
    },
    {
      id: 'gate_grilles_fences_railings',
      label: 'Gate, Grilles, Fences & Railings',
    },
    {
      id: 'gazebos_awnings_canopies_sheds',
      label: 'Gazebos, Awnings, Canopies & Sheds',
    },
    {
      id: 'geotextile_geogrids_pond_liners',
      label: 'Geotextile, Geogrids & Pond Liners',
    },
    {
      id: 'granite_marble_sandstone_others',
      label: 'Granite, Marble, Sandstone & Others',
    },
    {
      id: 'hardwood_flooring_wooden_floor_tiles',
      label: 'Hardwood Flooring & Wooden Floor Tiles',
    },
    {
      id: 'industrial_metal_fabrication',
      label: 'Industrial & Metal Fabrication',
    },
    {
      id: 'industrial_pipe_tube_fittings',
      label: 'Industrial Pipe & Tube Fittings',
    },
    {
      id: 'lifting_hooks_chains_clamps',
      label: 'Lifting Hooks, Chains & Clamps',
    },
    {
      id: 'metal_pipe_plumbing_fittings',
      label: 'Metal Pipe & Plumbing Fittings',
    },
    {
      id: 'pvc_cpvc_hdpe_water_pipe_fittings',
      label: 'Pvc, Cpvc, Hdpe Water Pipe Fittings',
    },
    {
      id: 'pvc_frp_hdpe_other_plastic_pipes',
      label: 'Pvc, Frp, Hdpe & Other Plastic Pipes',
    },
    {
      id: 'paints_wall_putty_varnishes',
      label: 'Paints, Wall Putty & Varnishes',
    },
    {
      id: 'prefabricated_houses_structures',
      label: 'Prefabricated Houses & Structures',
    },
    {
      id: 'roofing_and_false_ceiling',
      label: 'Roofing And False Ceiling',
    },
    {
      id: 'scaffolding_pipes_and_fittings',
      label: 'Scaffolding Pipes And Fittings',
    },
    {
      id: 'sewerage_and_drainage_product',
      label: 'Sewerage And Drainage Products',
    },
    {
      id: 'stained_etched_laminated_glass',
      label: 'Stained, Etched & Laminated Glass',
    },
    {
      id: 'staircase_balusters_and_stair_parts',
      label: 'Staircase, Balusters And Stair Parts',
    },
    {
      id: 'steel_bars_rods_plates_sheets',
      label: 'Steel Bars, Rods, Plates & Sheets',
    },
    { id: 'steel_pipes_and_tubes', label: 'Steel Pipes And Tubes' },
    { id: 'stone_tiles_floorings', label: 'Stone Tiles & Floorings' },
    {
      id: 'surface_coating_paint_equipment',
      label: 'Surface Coating & Paint Equipment',
    },
    {
      id: 'vinyl_plastic_rubber_floor_tiles',
      label: 'Vinyl, Plastic & Rubber Floor Tiles',
    },
    {
      id: 'vitrified_ceramic_floor_wall_tiles',
      label: 'Vitrified, Ceramic Floor & Wall Tiles',
    },
    { id: 'wire_mesh_gratings', label: 'Wire Mesh & Gratings' },
    {
      id: 'wood_plywood_veneer_laminates',
      label: 'Wood, Plywood, Veneer & Laminates',
    },
  ],
  'cosmetics-kids': [
    { id: 'baby_bath_nets', label: 'Baby Bath Nets' },
    { id: 'baby_creams_ointments', label: 'Baby Creams/Ointments' },
    { id: 'baby_scissors', label: 'Baby Scissors' },
    { id: 'baby_swipes', label: 'Baby Swipes' },
    { id: 'bed_protectors', label: 'Bed Protectors' },
    { id: 'body_oils', label: 'Body Oils' },
    { id: 'body_wash', label: 'Body Wash' },
    { id: 'breast_care', label: 'Breast Care' },
    { id: 'brush_comb', label: 'Brush/Comb' },
    { id: 'conditioner', label: 'Conditioner' },
    { id: 'diaper_bins', label: 'Diaper Bins' },
    { id: 'diaper_changing_mats', label: 'Diaper Changing Mats' },
    { id: 'diaper_monthly_pack', label: 'Diaper Monthly Pack' },
    { id: 'diaper_pants', label: 'Diaper Pants' },
    { id: 'diaper_rash_creams', label: 'Diaper Rash Creams' },
    { id: 'diaper_bags', label: 'Diaper Bags' },
    { id: 'ear_nose_nail_care', label: 'Ear/Nose/Nail Care' },
    { id: 'face_wash', label: 'Face Wash' },
    { id: 'grooming_kits', label: 'Grooming Kits' },
    { id: 'hair_oils', label: 'Hair Oils' },
    { id: 'hygiene', label: 'Hygiene' },
    { id: 'lotions', label: 'Lotions' },
    {
      id: 'maternity_anti_stretch_creams',
      label: 'Maternity Anti Stretch Creams',
    },
    { id: 'maternity_pads', label: 'Maternity Pads' },
    { id: 'napkins', label: 'Napkins' },
    { id: 'nappies', label: 'Nappies' },
    { id: 'nappy_inserts', label: 'Nappy Inserts' },
    { id: 'potty_chairs_seats', label: 'Potty Chairs/Seats' },
    { id: 'powder_puff', label: 'Powder Puff' },
    { id: 'powders', label: 'Powders' },
    { id: 'shampoo', label: 'Shampoo' },
    { id: 'shower_caps', label: 'Shower Caps' },
    { id: 'soap', label: 'Soap' },
    { id: 'swim_diapers', label: 'Swim Diapers' },
    { id: 'tools', label: 'Tools' },
    { id: 'wash_clothes', label: 'Wash Clothes' },
  ],
  'cosmetic-men': [
    { id: 'accessories', label: 'Accessories' },
    { id: 'bath_body', label: 'Bath/Body' },
    { id: 'bath_salts', label: 'Bath Salts' },
    { id: 'beard_cream', label: 'Beard Cream' },
    { id: 'beard_serum', label: 'Beard Serum' },
    { id: 'beard_softener', label: 'Beard Softener' },
    { id: 'beard_wash', label: 'Beard Wash' },
    { id: 'beard_wax', label: 'Beard Wax' },
    { id: 'beard_care', label: 'Beard Care' },
    { id: 'body_lotion', label: 'Body Lotion' },
    { id: 'body_spray_mist', label: 'Body Spray/Mist' },
    { id: 'cleanser', label: 'Cleanser' },
    { id: 'combos', label: 'Combos' },
    { id: 'compact_comb', label: 'Compact Comb' },
    { id: 'conditioner', label: 'Conditioner' },
    { id: 'dry_shampoo', label: 'Dry Shampoo' },
    { id: 'exfoliator_scrub', label: 'Exfoliator/Scrub' },
    { id: 'eye_cream', label: 'Eye Cream' },
    { id: 'face_mask', label: 'Face Mask' },
    { id: 'face_massagers', label: 'Face Massagers' },
    { id: 'face_wash', label: 'Face Wash' },
    { id: 'face_serum', label: 'Face Serum' },
    { id: 'fragrance', label: 'Fragrance' },
    { id: 'hair_mask', label: 'Hair Mask' },
    { id: 'hair_oils', label: 'Hair Oils' },
    { id: 'hair_powder', label: 'Hair Powder' },
    { id: 'hair_removal_creams', label: 'Hair Removal Creams' },
    { id: 'hair_serum', label: 'Hair Serum' },
    { id: 'hair_spa', label: 'Hair Spa' },
    { id: 'hair_styling_tool', label: 'Hair Styling Tool' },
    { id: 'hair_wax', label: 'Hair Wax' },
    { id: 'haircare', label: 'Haircare' },
    { id: 'haircare_kit', label: 'Haircare Kit' },
    { id: 'hand_wash', label: 'Hand Wash' },
    { id: 'hygiene', label: 'Hygiene' },
    { id: 'intimate_care', label: 'Intimate Care' },
    { id: 'makeup_brushes', label: 'Makeup Brushes' },
    { id: 'mask', label: 'Mask' },
    { id: 'moisturizer', label: 'Moisturizer' },
    { id: 'night_cream', label: 'Night Cream' },
    { id: 'pre_post_shave', label: 'Pre/Post Shave' },
    { id: 'razors_cartridges', label: 'Razors/Cartridges' },
    { id: 'shampoo', label: 'Shampoo' },
    { id: 'shave_soothing_gel', label: 'Shave Soothing Gel' },
    { id: 'shavers', label: 'Shavers' },
    { id: 'shaving_brushes', label: 'Shaving Brushes' },
    { id: 'shaving_cream', label: 'Shaving Cream' },
    { id: 'shaving_foam', label: 'Shaving Foam' },
    { id: 'shaving_lotion', label: 'Shaving Lotion' },
    { id: 'sheet_mask', label: 'Sheet Mask' },
    { id: 'shower_gels', label: 'Shower Gels' },
    { id: 'skin', label: 'Skin' },
    { id: 'skincare_kit', label: 'Skincare Kit' },
    { id: 'soaps', label: 'Soaps' },
    { id: 'styling_gel', label: 'Styling Gel' },
    { id: 'sunscreen', label: 'Sunscreen' },
    { id: 'tools', label: 'Tools' },
    { id: 'trimmers', label: 'Trimmers' },
    { id: 'under_eye_cream', label: 'Under Eye Cream' },
  ],
  'cosmetic-women': [
    { id: 'blush', label: 'Blush' },
    { id: 'body_lotion', label: 'Body Lotion' },
    { id: 'body_razors', label: 'Body Razors' },
    { id: 'body_spray_mist', label: 'Body Spray/Mist' },
    { id: 'bronzer', label: 'Bronzer' },
    { id: 'cartridges', label: 'Cartridges' },
    { id: 'cheek_stain', label: 'Cheek Stain' },
    { id: 'cleanser', label: 'Cleanser' },
    { id: 'comb', label: 'Comb' },
    { id: 'combos', label: 'Combos' },
    { id: 'concealer', label: 'Concealer' },
    { id: 'conditioner', label: 'Conditioner' },
    { id: 'deodorants', label: 'Deodorants' },
    { id: 'dry_shampoo', label: 'Dry Shampoo' },
    { id: 'epilators', label: 'Epilators' },
    { id: 'exfoliator_scrub', label: 'Exfoliator/Scrub' },
    { id: 'eye_combo', label: 'Eye Combo' },
    { id: 'eye_cream', label: 'Eye Cream' },
    { id: 'eye_shadow', label: 'Eye Shadow' },
    { id: 'eyebrow', label: 'Eyebrow' },
    { id: 'eyeliner', label: 'Eyeliner' },
    { id: 'eyes', label: 'Eyes' },
    { id: 'eyeshadow_brushes', label: 'Eyeshadow Brushes' },
    { id: 'face', label: 'Face' },
    { id: 'face_mask', label: 'Face Mask' },
    { id: 'face_massagers', label: 'Face Massagers' },
    { id: 'face_wash', label: 'Face Wash' },
    { id: 'face_eyebrow_razors', label: 'Face/Eyebrow Razors' },
    { id: 'face_serum', label: 'Face Serum' },
    { id: 'foot_cream', label: 'Foot Cream' },
    { id: 'foundation', label: 'Foundation' },
    { id: 'fragrance', label: 'Fragrance' },
    { id: 'glitter', label: 'Glitter' },
    { id: 'hair_colour', label: 'Hair Colour' },
    { id: 'hair_extension', label: 'Hair Extension' },
    { id: 'hair_mask', label: 'Hair Mask' },
    { id: 'hair_oils', label: 'Hair Oils' },
    { id: 'hair_removal_creams', label: 'Hair Removal Creams' },
    { id: 'hair_serum', label: 'Hair Serum' },
    { id: 'hair_spa', label: 'Hair Spa' },
    { id: 'hair_styling_tools', label: 'Hair Styling Tools' },
    { id: 'haircare_kit', label: 'Haircare Kit' },
    { id: 'hand_wash', label: 'Hand Wash' },
    { id: 'highlighter', label: 'Highlighter' },
    { id: 'hygiene', label: 'Hygiene' },
    { id: 'intimate_wash', label: 'Intimate Wash' },
    { id: 'kajal', label: 'Kajal' },
    { id: 'lip_balm', label: 'Lip Balm' },
    { id: 'lip_gloss', label: 'Lip Gloss' },
    { id: 'lip_kit', label: 'Lip Kit' },
    { id: 'lip_liner', label: 'Lip Liner' },
    { id: 'lips', label: 'Lips' },
    { id: 'lipstick', label: 'Lipstick' },
    { id: 'lipstick_set', label: 'Lipstick Set' },
    { id: 'makeup', label: 'Makeup' },
    { id: 'makeup_brushes', label: 'Makeup Brushes' },
    { id: 'makeup_remover', label: 'Makeup Remover' },
    { id: 'manicure_pedicure_tools', label: 'Manicure/Pedicure Tools' },
    { id: 'mascara', label: 'Mascara' },
    { id: 'mask', label: 'Mask' },
    { id: 'menstrual_cups', label: 'Menstrual Cups' },
    { id: 'moisturizer', label: 'Moisturizer' },
    { id: 'nail_art', label: 'Nail Art' },
    { id: 'nail_kit', label: 'Nail Kit' },
    { id: 'nail_paint_remover', label: 'Nail Paint Remover' },
    { id: 'nail_polish', label: 'Nail Polish' },
    { id: 'nails', label: 'Nails' },
    { id: 'night_cream', label: 'Night Cream' },
    { id: 'panty_liners', label: 'Panty Liners' },
    { id: 'perfumes', label: 'Perfumes' },
    { id: 'primer', label: 'Primer' },
    { id: 'sanitizing_kits', label: 'Sanitizing Kits' },
    { id: 'sanitizing_spray', label: 'Sanitizing Spray' },
    { id: 'sanitizing_wipes', label: 'Sanitizing Wipes' },
    { id: 'setting_compact_powder', label: 'Setting/Compact Powder' },
    { id: 'shampoo', label: 'Shampoo' },
    { id: 'sheet_mask', label: 'Sheet Mask' },
    { id: 'shower_gels', label: 'Shower Gels' },
    { id: 'skincare_kit', label: 'Skincare Kit' },
    { id: 'soaps', label: 'Soaps' },
    { id: 'sunscreen', label: 'Sunscreen' },
    { id: 'tampons', label: 'Tampons' },
    { id: 'tools', label: 'Tools' },
  ],
  digital_signature: [
    { id: 'class_2_individual', label: 'Class-2 Individual' },
    { id: 'class_3_both_sign_enc', label: 'Class-3 Both (Sign/Enc.)' },
    { id: 'class_3_encryption', label: 'Class-3 Encryption' },
    { id: 'class_3_individual', label: 'Class-3 Individual' },
    { id: 'class_3_organisation', label: 'Class-3 Organisation' },
    { id: 'dgft_certificate', label: 'DGFT Certificate' },
  ],
  electronics: [
    { id: 'air_conditioner', label: 'Air Conditioner' },
    { id: 'air_coolers', label: 'Air Coolers' },
    { id: 'air_purifiers', label: 'Air Purifiers' },
    { id: 'chimneys', label: 'Chimneys' },
    { id: 'dishwashers', label: 'Dishwashers' },
    { id: 'fan', label: 'Fan' },
    { id: 'fitness', label: 'Fitness' },
    { id: 'immersion_rods', label: 'Immersion Rods' },
    { id: 'inverters', label: 'Inverters' },
    { id: 'led_tv', label: 'Led Tv' },
    { id: 'microwave_oven', label: 'Microwave Oven' },
    { id: 'otg', label: 'Otg' },
    { id: 'refrigerator', label: 'Refrigerator' },
    { id: 'sewing_machine', label: 'Sewing Machine' },
    { id: 'smart_bands', label: 'Smart Bands' },
    { id: 'smart_watches', label: 'Smart Watches' },
    { id: 'vacuum_cleaners', label: 'Vacuum Cleaners' },
    { id: 'voltage_stabilizers', label: 'Voltage Stabilizers' },
    { id: 'washing_machine', label: 'Washing Machine' },
    { id: 'water_geysers', label: 'Water Geysers' },
    { id: 'water_purifiers', label: 'Water Purifiers' },
  ],
  financial_services: [
    { id: 'mutual_fund_agent', label: 'Mutual Fund agent' },
    { id: 'stock_broker', label: 'Stock Broker' },
    { id: 'wealth_management', label: 'Wealth Management' },
    { id: 'life_insurance', label: 'Life Insurance' },
    { id: 'non_life_insurance', label: 'Non-Life insurance' },
    { id: 'nbfc_agent', label: 'NBFC Agent' },
    { id: 'scholarships', label: 'Scholarships' },
  ],
  food_and_beverages: [
    { id: 'aerated_drinks', label: 'Aerated Drinks' },
    {
      id: 'ayurvedic_herbal_health_supplement',
      label: 'Ayurvedic & Herbal Health Supplement',
    },
    { id: 'chips', label: 'Chips' },
    {
      id: 'chocolates_biscuits_cookies',
      label: 'Chocolates, Biscuits & Cookies',
    },
    { id: 'drinking_water', label: 'Drinking Water' },
    { id: 'fruit_drinks', label: 'Fruit Drinks' },
    { id: 'indian_sweets_desserts', label: 'Indian Sweets & Desserts' },
    {
      id: 'juices_soups_soft_drinks',
      label: 'Juices, Soups & Soft Drinks',
    },
    { id: 'mineral_water', label: 'Mineral Water' },
    { id: 'pickles_jams_ketchups', label: 'Pickles, Jams & Ketchups' },
    { id: 'salted_snacks', label: 'Salted Snacks' },
    { id: 'snacks_and_namkeen', label: 'Snacks And Namkeen' },
    { id: 'veg_snacks', label: 'Veg Snacks' },
    { id: 'carbonated_drinks', label: 'Carbonated Drinks' },
  ],
  footwear: [
    { id: 'bellies', label: 'Bellies' },
    { id: 'boots', label: 'Boots' },
    { id: 'casuals', label: 'Casuals' },
    { id: 'clogs', label: 'Clogs' },
    { id: 'flats', label: 'Flats' },
    { id: 'flip_flops', label: 'Flip Flops' },
    { id: 'floaters', label: 'Floaters' },
    { id: 'formals', label: 'Formals' },
    { id: 'heels', label: 'Heels' },
    { id: 'mojaris', label: 'Mojaris' },
    { id: 'sandals', label: 'Sandals' },
    { id: 'skates', label: 'Skates' },
    { id: 'sneakers', label: 'Sneakers' },
    { id: 'sports', label: 'Sports' },
  ],
  gardening: [
    { id: 'balcony_gardening', label: 'Balcony Gardening' },
    { id: 'butterfly_gardening', label: 'Butterfly Gardening' },
    { id: 'garden_hand_tools', label: 'Garden Hand Tools' },
    { id: 'garden_tools', label: 'Garden Tools' },
    { id: 'terrace_gardening', label: 'Terrace Gardening' },
    { id: 'vertical_garden', label: 'Vertical Garden' },
  ],
  hardware: [
    {
      id: 'bath_tubs_jacuzzi_hot_tubs',
      label: 'Bath Tubs, Jacuzzi & Hot Tubs',
    },
    {
      id: 'brackets_holder_hardware_fittings',
      label: 'Brackets, Holder & Hardware Fittings',
    },
    {
      id: 'curtain_and_drapery_hardware',
      label: 'Curtain And Drapery Hardware',
    },
    {
      id: 'door_window_hinges_fittings',
      label: 'Door & Window, Hinges & Fittings',
    },
    {
      id: 'door_lock_electronic_lock_latches',
      label: 'Door Lock, Electronic Lock & Latches',
    },
    {
      id: 'faucets_water_taps_and_bib_cocks',
      label: 'Faucets, Water Taps And Bib Cocks',
    },
    { id: 'hardware_hooks_mounts', label: 'Hardware: Hooks & Mounts' },
    {
      id: 'nails_fasteners_rivets_shackles',
      label: 'Nails, Fasteners, Rivets & Shackles',
    },
    {
      id: 'pipe_elbows_joints_couplings',
      label: 'Pipe Elbows, Joints & Couplings',
    },
    { id: 'shower_panels_accessories', label: 'Shower Panels & Accessories' },
    {
      id: 'wash_basins_sanitary_ware_fittings',
      label: 'Wash Basins, Sanitary Ware & Fittings',
    },
  ],
  heavy_tools: [
    {
      id: 'adhesive_pressure_sensitive_tapes',
      label: 'Adhesive & Pressure Sensitive Tapes',
    },
    {
      id: 'adhesives_glue_and_sealants',
      label: 'Adhesives, Glue And Sealants',
    },
    {
      id: 'air_springs_compression_springs',
      label: 'Air Springs & Compression Springs',
    },
    {
      id: 'aluminum_brass_bronze_pipes',
      label: 'Aluminum, Brass, Bronze Pipes',
    },
    {
      id: 'ball_bearings_and_bearing_assemblies',
      label: 'Ball Bearings And Bearing Assemblies',
    },
    {
      id: 'bar_neodymium_permanent_magnets',
      label: 'Bar, Neodymium & Permanent Magnets',
    },
    {
      id: 'batteries_charge_storage_devices',
      label: 'Batteries & Charge Storage Devices',
    },
    { id: 'boilers_boiler_parts', label: 'Boilers & Boiler Parts' },
    {
      id: 'brackets_holder_hardware_fittings',
      label: 'Brackets, Holder & Hardware Fittings',
    },
    { id: 'carts_dollies_trolleys', label: 'Carts, Dollies & Trolleys' },
    {
      id: 'chisels_professional_hand_tools',
      label: 'Chisels & Professional Hand Tools',
    },
    {
      id: 'clutch_clutch_parts_accessories',
      label: 'Clutch, Clutch Parts & Accessories',
    },
    {
      id: 'die_casting_investment_castings',
      label: 'Die Casting & Investment Castings',
    },
    {
      id: 'disinfection_equipment_machines',
      label: 'Disinfection Equipment & Machines',
    },
    {
      id: 'drilling_bits_collets_and_chucks',
      label: 'Drilling Bits, Collets And Chucks',
    },
    {
      id: 'drills_grinders_saws_power_tools',
      label: 'Drills, Grinders, Saws & Power Tools',
    },
    { id: 'dryers_evaporators', label: 'Dryers & Evaporators' },
    {
      id: 'electric_circuit_components_spares',
      label: 'Electric Circuit Components & Spares',
    },
    {
      id: 'electric_fittings_components',
      label: 'Electric Fittings & Components',
    },
    {
      id: 'electric_motors_and_components',
      label: 'Electric Motors And Components',
    },
    {
      id: 'electrical_conduits_and_fittings',
      label: 'Electrical Conduits And Fittings',
    },
    { id: 'elevators_escalators', label: 'Elevators & Escalators' },
    { id: 'enclosures_cabinets', label: 'Enclosures & Cabinets' },
    {
      id: 'engineering_and_shipping_ropes',
      label: 'Engineering And Shipping Ropes',
    },
    { id: 'fiber_glass_product', label: 'Fiber Glass Products' },
    {
      id: 'filters_filtration_systems',
      label: 'Filters & Filtration Systems',
    },
    {
      id: 'fire_fighting_prevention_product',
      label: 'Fire Fighting & Prevention Products',
    },
    { id: 'flanges_flanged_fittings', label: 'Flanges & Flanged Fittings' },
    {
      id: 'forgings_forging_parts_supplies',
      label: 'Forgings, Forging Parts & Supplies',
    },
    {
      id: 'freezers_refrigerators_chillers',
      label: 'Freezers, Refrigerators & Chillers',
    },
    {
      id: 'gearbox_axle_sprocket_gear_parts',
      label: 'Gearbox, Axle, Sprocket & Gear Parts',
    },
    {
      id: 'heater_thermostat_heating_devices',
      label: 'Heater, Thermostat & Heating Devices',
    },
    {
      id: 'heavy_light_duty_caster_wheels',
      label: 'Heavy & Light Duty Caster Wheels',
    },
    { id: 'hoses_hose_fittings', label: 'Hoses & Hose Fittings' },
    {
      id: 'hydraulic_jacks_lifts_winches',
      label: 'Hydraulic Jacks, Lifts & Winches',
    },
    {
      id: 'industrial_engineering_goods',
      label: 'Industrial & Engineering Goods',
    },
    {
      id: 'industrial_machine_brushes',
      label: 'Industrial & Machine Brushes',
    },
    {
      id: 'industrial_metal_fabrication',
      label: 'Industrial & Metal Fabrication',
    },
    {
      id: 'industrial_air_conditioner_devices',
      label: 'Industrial Air Conditioner & Devices',
    },
    { id: 'industrial_belts_v_belts', label: 'Industrial Belts & V Belts' },
    {
      id: 'industrial_coolers_blowers_fans',
      label: 'Industrial Coolers, Blowers & Fans',
    },
    {
      id: 'industrial_pipe_tube_fittings',
      label: 'Industrial Pipe & Tube Fittings',
    },
    {
      id: 'industrial_racks_storage_system',
      label: 'Industrial Racks & Storage System',
    },
    {
      id: 'industrial_valves_valve_fittings',
      label: 'Industrial Valves & Valve Fittings',
    },
    {
      id: 'instrument_calibration_adjustment',
      label: 'Instrument Calibration & Adjustment',
    },
    {
      id: 'insulators_insulation_materials',
      label: 'Insulators & Insulation Materials',
    },
    {
      id: 'lifting_hooks_chains_clamps',
      label: 'Lifting Hooks, Chains & Clamps',
    },
    {
      id: 'lubrication_systems_and_equipment',
      label: 'Lubrication Systems And Equipment',
    },
    {
      id: 'manufacturing_assembling_services',
      label: 'Manufacturing & Assembling Services',
    },
    {
      id: 'material_testing_labs_services',
      label: 'Material Testing Labs & Services',
    },
    {
      id: 'measurement_gauges_gauge_fittings',
      label: 'Measurement Gauges & Gauge Fittings',
    },
    {
      id: 'metal_plastic_moulding_services',
      label: 'Metal & Plastic Moulding Services',
    },
    {
      id: 'metal_finishing_coating_services',
      label: 'Metal Finishing & Coating Services',
    },
    {
      id: 'metal_pipe_plumbing_fittings',
      label: 'Metal Pipe & Plumbing Fittings',
    },
    {
      id: 'metal_scrap_waste_materials',
      label: 'Metal Scrap & Waste Materials',
    },
    {
      id: 'metal_security_safety_detectors',
      label: 'Metal, Security & Safety Detectors',
    },
    {
      id: 'moulds_jigs_and_casting_dies',
      label: 'Moulds, Jigs And Casting Dies',
    },
    {
      id: 'nails_fasteners_rivets_shackles',
      label: 'Nails, Fasteners, Rivets & Shackles',
    },
    { id: 'oils_grease_lubricants', label: 'Oils, Grease & Lubricants' },
    {
      id: 'pipe_elbows_joints_couplings',
      label: 'Pipe Elbows, Joints & Couplings',
    },
    {
      id: 'piston_crankshaft_assemblies',
      label: 'Piston & Crankshaft Assemblies',
    },
    { id: 'plastic_rubber_product', label: 'Plastic & Rubber Products' },
    { id: 'plastic_pvc_pp_product', label: 'Plastic, Pvc & Pp Products' },
    {
      id: 'product_engineering_and_prototyping',
      label: 'Product Engineering And Prototyping',
    },
    {
      id: 'pumps_pumping_machines_spares',
      label: 'Pumps, Pumping Machines & Spares',
    },
    {
      id: 'pvc_cpvc_hdpe_water_pipe_fittings',
      label: 'Pvc, Cpvc, Hdpe Water Pipe Fittings',
    },
    {
      id: 'pvc_frp_hdpe_other_plastic_pipes',
      label: 'Pvc, Frp, Hdpe & Other Plastic Pipes',
    },
    {
      id: 'pvc_ldpe_hdpe_plastic_sheets',
      label: 'Pvc, Ldpe, Hdpe & Plastic Sheets',
    },
    { id: 'rubber_rubber_product', label: 'Rubber & Rubber Products' },
    {
      id: 'rubber_gaskets_and_gasket_material',
      label: 'Rubber Gaskets And Gasket Material',
    },
    {
      id: 'rust_corrosion_protection_product',
      label: 'Rust & Corrosion Protection Products',
    },
    {
      id: 'seals_oil_seals_industrial_seals',
      label: 'Seals, Oil Seals & Industrial Seals',
    },
    {
      id: 'separators_strainers_purifiers',
      label: 'Separators, Strainers & Purifiers',
    },
    {
      id: 'sheet_metal_turned_components',
      label: 'Sheet Metal & Turned Components',
    },
    { id: 'smoke_gas_leak_detectors', label: 'Smoke & Gas Leak Detectors' },
    {
      id: 'stained_etched_laminated_glass',
      label: 'Stained, Etched & Laminated Glass',
    },
    {
      id: 'stamping_tools_stamping_machine',
      label: 'Stamping Tools & Stamping Machine',
    },
    {
      id: 'steel_stainless_steel_product',
      label: 'Steel & Stainless Steel Products',
    },
    {
      id: 'steel_bars_rods_plates_sheets',
      label: 'Steel Bars, Rods, Plates & Sheets',
    },
    { id: 'steel_pipes_and_tubes', label: 'Steel Pipes And Tubes' },
    {
      id: 'storage_tanks_drums_containers',
      label: 'Storage Tanks, Drums & Containers',
    },
    {
      id: 'welding_rods_electrodes_wires',
      label: 'Welding, Rods, Electrodes & Wires',
    },
    {
      id: 'welding_soldering_brazing_service',
      label: 'Welding, Soldering & Brazing Service',
    },
    { id: 'wire_mesh_gratings', label: 'Wire Mesh & Gratings' },
  ],
  herbal_nutrition: [
    { id: 'beauty_skin', label: 'Beauty Skin' },
    { id: 'blood_pressure', label: 'Blood Pressure' },
    { id: 'blood_purifiers', label: 'Blood Purifiers' },
    { id: 'cough_fighter', label: 'Cough Fighter' },
    { id: 'detox', label: 'Detox' },
    { id: 'energy_boosters', label: 'Energy Boosters' },
    { id: 'hair_supplements', label: 'Hair Supplements' },
    { id: 'health_supplements', label: 'Health Supplements' },
    { id: 'herbal_juices_drinks', label: 'Herbal Juices/Drinks' },
    { id: 'immunity_builders', label: 'Immunity Builders' },
    { id: 'maternity_supplements', label: 'Maternity Supplements' },
    { id: 'mental_wellness', label: 'Mental Wellness' },
    { id: 'milk_powders', label: 'Milk Powders' },
    { id: 'organs_health', label: 'Organs Health' },
    { id: 'pcod', label: 'PCOD' },
    { id: 'performance_boosters', label: 'Performance Boosters' },
    { id: 'protein', label: 'Protein' },
    { id: 'ubtan', label: 'Ubtan' },
  ],
  home_decor: [
    { id: 'baby_mattresses', label: 'Baby Mattresses' },
    { id: 'basins', label: 'Basins' },
    { id: 'bath_spa', label: 'Bath & Spa' },
    { id: 'bath_towels', label: 'Bath Towels' },
    { id: 'bathroom', label: 'Bathroom' },
    { id: 'bathroom_accessories', label: 'Bathroom Accessories' },
    { id: 'bathroom_cabinets', label: 'Bathroom Cabinets' },
    { id: 'bathroom_mirrors', label: 'Bathroom Mirrors' },
    { id: 'bean_bag', label: 'Bean Bag' },
    { id: 'bed_linen', label: 'Bed Linen' },
    { id: 'bedroom', label: 'Bedroom' },
    { id: 'beds', label: 'Beds' },
    { id: 'benches', label: 'Benches' },
    { id: 'book_shelf', label: 'Book Shelf' },
    { id: 'bulbs', label: 'Bulbs' },
    { id: 'bunk_beds', label: 'Bunk Beds' },
    { id: 'carpet', label: 'Carpet' },
    { id: 'ceiling_lamp', label: 'Ceiling Lamp' },
    { id: 'chairs', label: 'Chairs' },
    { id: 'chest_drawers', label: 'Chest Drawers' },
    { id: 'coffee_tables', label: 'Coffee Tables' },
    { id: 'cribs', label: 'Cribs' },
    { id: 'crockery_units', label: 'Crockery Units' },
    { id: 'cubicles', label: 'Cubicles' },
    { id: 'curtain', label: 'Curtain' },
    { id: 'cushion_and_cover', label: 'Cushion And Cover' },
    { id: 'decor_accessories', label: 'Decor Accessories' },
    { id: 'dining_chairs', label: 'Dining Chairs' },
    { id: 'dining_tables', label: 'Dining Tables' },
    { id: 'divan', label: 'Divan' },
    { id: 'door_hangings', label: 'Door Hangings' },
    { id: 'dressing_table', label: 'Dressing Table' },
    { id: 'emergency_light', label: 'Emergency Light' },
    { id: 'essentials', label: 'Essentials' },
    { id: 'faucets', label: 'Faucets' },
    { id: 'floor_covering', label: 'Floor Covering' },
    { id: 'floor_lights', label: 'Floor Lights' },
    { id: 'futons', label: 'Futons' },
    { id: 'home_garden', label: 'Home Garden' },
    { id: 'home_temples', label: 'Home Temples' },
    { id: 'iconic_chairs', label: 'Iconic Chairs' },
    { id: 'idols', label: 'Idols' },
    { id: 'installation_system', label: 'Installation System' },
    { id: 'kids_bedroom', label: 'Kids Bedroom' },
    { id: 'kids_beds', label: 'Kids Beds' },
    { id: 'kids_bookshelf', label: 'Kids Bookshelf' },
    { id: 'kids_seating', label: 'Kids Seating' },
    { id: 'kids_storage', label: 'Kids Storage' },
    { id: 'kids_wardrobes', label: 'Kids Wardrobes' },
    { id: 'kitchen', label: 'Kitchen' },
    { id: 'kitchen_cabinets', label: 'Kitchen Cabinets' },
    { id: 'kitchen_island', label: 'Kitchen Island' },
    { id: 'kitchen_racks', label: 'Kitchen Racks' },
    { id: 'kitchen_shelves', label: 'Kitchen Shelves' },
    { id: 'kitchen_trolleys', label: 'Kitchen Trolleys' },
    { id: 'lighting_decor', label: 'Lighting/Decor' },
    { id: 'living_room', label: 'Living Room' },
    { id: 'mattresses', label: 'Mattresses' },
    { id: 'microwave_stands', label: 'Microwave Stands' },
    { id: 'modular_kitchen', label: 'Modular Kitchen' },
    { id: 'office_chairs', label: 'Office Chairs' },
    { id: 'office_furniture', label: 'Office Furniture' },
    { id: 'office_table', label: 'Office Table' },
    { id: 'pillows', label: 'Pillows' },
    { id: 'reception_furniture', label: 'Reception Furniture' },
    { id: 'recliners', label: 'Recliners' },
    { id: 'robe_hooks', label: 'Robe Hooks' },
    { id: 'room_dividers', label: 'Room Dividers' },
    { id: 'seats_and_covers', label: 'Seats And Covers' },
    { id: 'shelves', label: 'Shelves' },
    { id: 'shoe_racks', label: 'Shoe Racks' },
    { id: 'shower', label: 'Shower' },
    { id: 'smart_door_locks', label: 'Smart Door Locks' },
    { id: 'smart_home', label: 'Smart Home' },
    { id: 'smart_security_systems', label: 'Smart Security Systems' },
    { id: 'soap_dishes', label: 'Soap Dishes' },
    { id: 'soap_dispenser', label: 'Soap Dispenser' },
    { id: 'sofa', label: 'Sofa' },
    { id: 'sofa_beds', label: 'Sofa Beds' },
    { id: 'space_saving_furniture', label: 'Space Saving Furniture' },
    { id: 'spiritual', label: 'Spiritual' },
    { id: 'stickers', label: 'Stickers' },
    { id: 'stool', label: 'Stool' },
    { id: 'storage', label: 'Storage' },
    { id: 'study_tables', label: 'Study Tables' },
    { id: 'table_lamp', label: 'Table Lamp' },
    { id: 'table_linen', label: 'Table Linen' },
    { id: 'table_showpieces_figurines', label: 'Table Showpieces/Figurines' },
    { id: 'toilet', label: 'Toilet' },
    { id: 'toilet_roll_holder', label: 'Toilet Roll Holder' },
    { id: 'towel_rails', label: 'Towel Rails' },
    { id: 'towel_rings', label: 'Towel Rings' },
    { id: 'tv_units', label: 'Tv Units' },
    { id: 'urinals', label: 'Urinals' },
    { id: 'wall_accents', label: 'Wall Accents' },
    { id: 'wall_arts', label: 'Wall Arts' },
    { id: 'wall_lamp', label: 'Wall Lamp' },
    { id: 'wardrobes', label: 'Wardrobes' },
    { id: 'writing_board', label: 'Writing Board' },
  ],
  kitchen_appliances: [
    { id: 'blender', label: 'Blender' },
    { id: 'air_fryer', label: 'Air Fryer' },
    { id: 'atta_kneader', label: 'Atta Kneader' },
    { id: 'chimney', label: 'Chimney' },
    { id: 'electric_chopper', label: 'Electric Chopper' },
    { id: 'flour_mill', label: 'Flour Mill' },
    { id: 'food_processor', label: 'Food Processor' },
    { id: 'gas_stove', label: 'Gas Stove' },
    { id: 'ice_cream_maker', label: 'Ice Cream Maker' },
    { id: 'ice_shaver', label: 'Ice Shaver' },
    { id: 'induction_cooktop', label: 'Induction Cooktop' },
    { id: 'iron', label: 'Iron' },
    { id: 'juicer', label: 'Juicer' },
    { id: 'kettle', label: 'Kettle' },
    { id: 'mixer_grinder', label: 'Mixer Grinder' },
    { id: 'other_appliances', label: 'Other Appliances' },
    { id: 'popcorn_maker', label: 'Popcorn Maker' },
    { id: 'sandwich_maker', label: 'Sandwich Maker' },
    { id: 'soda_maker', label: 'Soda Maker' },
    { id: 'tea_and_coffee_maker', label: 'Tea And Coffee Maker' },
    { id: 'toaster', label: 'Toaster' },
    { id: 'waffle_maker', label: 'Waffle Maker' },
    { id: 'water_purifier', label: 'Water Purifier' },
  ],
  kitchen_ware: [
    { id: 'apron', label: 'Apron' },
    { id: 'bake_ware', label: 'Bake Ware' },
    { id: 'baking_combo', label: 'Baking Combo' },
    { id: 'baking_mould', label: 'Baking Mould' },
    { id: 'baking_tools', label: 'Baking Tools' },
    { id: 'bottle_flask', label: 'Bottle/Flask' },
    { id: 'bowl', label: 'Bowl' },
    { id: 'casserole', label: 'Casserole' },
    { id: 'ceramic_ware', label: 'Ceramic Ware' },
    { id: 'chakla_belan', label: 'Chakla Belan' },
    { id: 'chopper_cutter', label: 'Chopper/Cutter' },
    { id: 'chopping_board', label: 'Chopping Board' },
    { id: 'cooking_tools', label: 'Cooking Tools' },
    { id: 'cookware', label: 'Cookware' },
    { id: 'cookware_set', label: 'Cookware Set' },
    { id: 'crockery', label: 'Crockery' },
    { id: 'cutlery', label: 'Cutlery' },
    { id: 'dinner_set', label: 'Dinner-set' },
    { id: 'dinnerware', label: 'Dinnerware' },
    { id: 'earthen_ware', label: 'Earthen Ware' },
    { id: 'fry_pan', label: 'Fry Pan' },
    { id: 'gas_stove_accessories', label: 'Gas Stove Accessories' },
    { id: 'glassware', label: 'Glassware' },
    { id: 'handi', label: 'Handi' },
    { id: 'idli_cooker', label: 'Idli Cooker' },
    { id: 'jar_container', label: 'Jar/Container' },
    { id: 'jug_carafe', label: 'Jug/Carafe' },
    { id: 'juicer', label: 'Juicer' },
    { id: 'kadhai', label: 'Kadhai' },
    { id: 'khalbatta', label: 'Khalbatta' },
    { id: 'kitchen_decor', label: 'Kitchen Decor' },
    { id: 'kitchen_tools', label: 'Kitchen Tools' },
    { id: 'masala_box', label: 'Masala Box' },
    { id: 'oil_can', label: 'Oil Can' },
    { id: 'organiser', label: 'Organiser' },
    { id: 'other', label: 'Other' },
    { id: 'ovenware', label: 'Ovenware' },
    { id: 'peeler_knife', label: 'Peeler/Knife' },
    { id: 'plates', label: 'Plates' },
    { id: 'pressure_cooker', label: 'Pressure Cooker' },
    { id: 'rice_cooker', label: 'Rice Cooker' },
    { id: 'sauce_pan', label: 'Sauce Pan' },
    { id: 'serving_tools', label: 'Serving Tools' },
    { id: 'slicer_grater', label: 'Slicer/Grater' },
    { id: 'stainless_steel_utensils', label: 'Stainless Steel Utensils' },
    { id: 'storage', label: 'Storage' },
    { id: 'tawa', label: 'Tawa' },
    { id: 'tiffin_lunch_box', label: 'Tiffin/Lunch Box' },
    { id: 'tongs', label: 'Tongs' },
    { id: 'tope_tapeli', label: 'Tope (Tapeli)' },
    { id: 'tray', label: 'Tray' },
    { id: 'water_pot', label: 'Water Pot' },
    { id: 'water_juice_glasses', label: 'Water/Juice Glasses' },
  ],
  machinery: [
    { id: 'apparel_textile_machinery', label: 'Apparel & Textile Machinery' },
    { id: 'asphalt_road_equipment', label: 'Asphalt Road Equipment' },
    { id: 'bakery_dairy_machinery', label: 'Bakery & Dairy Machinery' },
    {
      id: 'bar_neodymium_permanent_magnets',
      label: 'Bar, Neodymium & Permanent Magnets',
    },
    {
      id: 'bending_metalwork_machines',
      label: 'Bending & Metalwork Machines',
    },
    { id: 'bending_machine', label: 'Bending Machine' },
    {
      id: 'binding_and_pressing_machines',
      label: 'Binding And Pressing Machines',
    },
    { id: 'block_making_machine', label: 'Block Making Machine' },
    { id: 'boilers_boiler_parts', label: 'Boilers & Boiler Parts' },
    { id: 'brick_making_machines', label: 'Brick Making Machines' },
    {
      id: 'building_construction_cleaning_machine',
      label: 'Building & Construction Cleaning Machine',
    },
    { id: 'building_tools', label: 'Building Tools' },
    {
      id: 'cad_cam_design_consultancy',
      label: 'Cad Cam Design & Consultancy',
    },
    {
      id: 'casting_moulding_forging_machines',
      label: 'Casting, Moulding & Forging Machines',
    },
    { id: 'chemical_plants_machinery', label: 'Chemical Plants & Machinery' },
    {
      id: 'chemical_reactors_and_process_tanks',
      label: 'Chemical Reactors And Process Tanks',
    },
    {
      id: 'cnc_machines_lathe_machine',
      label: 'Cnc Machines & Lathe Machine',
    },
    { id: 'concrete_equipment', label: 'Concrete Equipment' },
    { id: 'concrete_mixer', label: 'Concrete Mixer' },
    { id: 'concrete_mold', label: 'Concrete Mold' },
    { id: 'concrete_pumps', label: 'Concrete Pumps' },
    { id: 'construction_equipment', label: 'Construction Equipment' },
    { id: 'construction_machines', label: 'Construction Machines' },
    { id: 'control_equipments', label: 'Control Equipments' },
    {
      id: 'conveyor_systems_components',
      label: 'Conveyor Systems & Components',
    },
    {
      id: 'cooling_tower_heat_exchanger_parts',
      label: 'Cooling Tower, Heat Exchanger, Parts',
    },
    {
      id: 'cranes_forklift_lifting_machines',
      label: 'Cranes, Forklift & Lifting Machines',
    },
    { id: 'crusher_shredder_presses', label: 'Crusher, Shredder & Presses' },
    { id: 'crushing_machines_plants', label: 'Crushing Machines & Plants' },
    {
      id: 'cutting_machines_equipment',
      label: 'Cutting Machines & Equipment',
    },
    { id: 'decoiler', label: 'Decoiler' },
    { id: 'drilling_boring_equipment', label: 'Drilling & Boring Equipment' },
    { id: 'drum_mixers', label: 'Drum Mixers' },
    { id: 'dryers_evaporators', label: 'Dryers & Evaporators' },
    { id: 'elevators_escalators', label: 'Elevators & Escalators' },
    {
      id: 'excavator_and_earth_moving_machinery',
      label: 'Excavator And Earth Moving Machinery',
    },
    {
      id: 'extraction_plants_and_extruders',
      label: 'Extraction Plants And Extruders',
    },
    {
      id: 'farming_tools_equipment_machines',
      label: 'Farming Tools, Equipment & Machines',
    },
    {
      id: 'fast_food_beverages_machinery',
      label: 'Fast Food & Beverages Machinery',
    },
    {
      id: 'food_grains_nut_processing_machine',
      label: 'Food Grains & Nut Processing Machine',
    },
    {
      id: 'food_processing_plants_machinery',
      label: 'Food Processing Plants & Machinery',
    },
    {
      id: 'freezers_refrigerators_chillers',
      label: 'Freezers, Refrigerators & Chillers',
    },
    {
      id: 'fruit_vegetable_processing_machine',
      label: 'Fruit & Vegetable Processing Machine',
    },
    {
      id: 'heater_thermostat_heating_devices',
      label: 'Heater, Thermostat & Heating Devices',
    },
    {
      id: 'hydraulic_pneumatic_machines',
      label: 'Hydraulic & Pneumatic Machines',
    },
    {
      id: 'hydraulic_jacks_lifts_winches',
      label: 'Hydraulic Jacks, Lifts & Winches',
    },
    {
      id: 'industrial_coolers_blowers_fans',
      label: 'Industrial Coolers, Blowers & Fans',
    },
    { id: 'industrial_furnaces_ovens', label: 'Industrial Furnaces & Ovens' },
    {
      id: 'lubrication_systems_and_equipment',
      label: 'Lubrication Systems And Equipment',
    },
    {
      id: 'material_handling_machines_systems',
      label: 'Material Handling Machines & Systems',
    },
    {
      id: 'meat_seafood_processing_equipments',
      label: 'Meat & Seafood Processing Equipments',
    },
    { id: 'milling_grinding_tools', label: 'Milling & Grinding Tools' },
    { id: 'mobile_concrete_mixers', label: 'Mobile Concrete Mixers' },
    {
      id: 'oil_mill_oil_extraction_machinery',
      label: 'Oil Mill & Oil Extraction Machinery',
    },
    {
      id: 'oxygen_nitrogen_gas_plants',
      label: 'Oxygen & Nitrogen Gas Plants',
    },
    {
      id: 'packaging_lamination_machinery',
      label: 'Packaging & Lamination Machinery',
    },
    { id: 'paper_work_making_machine', label: 'Paper Work & Making Machine' },
    { id: 'paver_machine', label: 'Paver Machine' },
    {
      id: 'pharmaceutical_machinery_equipment',
      label: 'Pharmaceutical Machinery & Equipment',
    },
    {
      id: 'plastic_work_processing_machines',
      label: 'Plastic Work & Processing Machines',
    },
    {
      id: 'pollution_control_devices_machines',
      label: 'Pollution Control Devices & Machines',
    },
    {
      id: 'printing_machinery_equipment',
      label: 'Printing Machinery & Equipment',
    },
    {
      id: 'product_engineering_and_prototyping',
      label: 'Product Engineering And Prototyping',
    },
    { id: 'road_construction_machine', label: 'Road Construction Machine' },
    { id: 'road_marking_machine', label: 'Road Marking Machine' },
    { id: 'road_roller', label: 'Road Roller' },
    {
      id: 'rubber_processing_tyre_machinery',
      label: 'Rubber Processing, Tyre Machinery',
    },
    {
      id: 'sewing_knitting_embroidery_machine',
      label: 'Sewing,Knitting & Embroidery Machine',
    },
    { id: 'straightening_machines', label: 'Straightening Machines' },
    {
      id: 'strapping_sealing_machines',
      label: 'Strapping & Sealing Machines',
    },
    {
      id: 'surface_coating_paint_equipment',
      label: 'Surface Coating & Paint Equipment',
    },
    {
      id: 'testing_measuring_equipments',
      label: 'Testing & Measuring Equipments',
    },
    { id: 'thread_rolling_machine', label: 'Thread Rolling Machine' },
    { id: 'tile_making_machine', label: 'Tile Making Machine' },
    {
      id: 'turnkey_consultants_solutions',
      label: 'Turnkey Consultants & Solutions',
    },
    {
      id: 'vending_machines_dispensers',
      label: 'Vending Machines & Dispensers',
    },
    {
      id: 'vfd_plc_hmi_control_equipments',
      label: 'Vfd, Plc, Hmi & Control Equipments',
    },
    { id: 'vibratory_compactors', label: 'Vibratory Compactors' },
    {
      id: 'water_treatment_purification_plant',
      label: 'Water Treatment & Purification Plant',
    },
    {
      id: 'welding_equipments_machinery',
      label: 'Welding Equipments & Machinery',
    },
    {
      id: 'wire_drawing_cabling_machines',
      label: 'Wire Drawing & Cabling Machines',
    },
    { id: 'working_platform', label: 'Working Platform' },
  ],
  packaging: [
    { id: 'adhesives', label: 'Adhesives' },
    { id: 'aluminum_foil', label: 'Aluminum Foil' },
    { id: 'blister_trey', label: 'Blister Trey' },
    { id: 'bubble_wrap', label: 'Bubble Wrap' },
    { id: 'cardboard_boxes', label: 'Cardboard Boxes' },
    { id: 'cling_film', label: 'Cling Film' },
    { id: 'corrugated_box', label: 'Corrugated Box' },
    {
      id: 'cosmetic_packaging_material',
      label: 'Cosmetic Packaging Material',
    },
    { id: 'cushioning_material', label: 'Cushioning Material' },
    { id: 'dispenser_pumps', label: 'Dispenser Pumps' },
    { id: 'food_packaging_material', label: 'Food Packaging Material' },
    { id: 'gift_box', label: 'Gift Box' },
    { id: 'glass_containers', label: 'Glass Containers' },
    { id: 'jute_bags', label: 'Jute Bags' },
    { id: 'labels', label: 'Labels' },
    { id: 'pet_bottle', label: 'Pet Bottle' },
    { id: 'pp_straps', label: 'Pp Straps' },
    { id: 'paper_bag', label: 'Paper Bag' },
    { id: 'parchment_paper', label: 'Parchment Paper' },
    { id: 'plastic_container', label: 'Plastic Container' },
    { id: 'plastic_crates', label: 'Plastic Crates' },
    { id: 'plastic_jars', label: 'Plastic Jars' },
    { id: 'plastic_trey', label: 'Plastic Trey' },
    { id: 'plastic_wrap', label: 'Plastic Wrap' },
    { id: 'printing_ink', label: 'Printing Ink' },
    { id: 'recyclable_material', label: 'Recyclable Material' },
    { id: 'shrink_wrap', label: 'Shrink Wrap' },
    { id: 'tapes', label: 'Tapes' },
    { id: 'tetra_pack_board', label: 'Tetra Pack Board' },
    { id: 'thermoplastics', label: 'Thermoplastics' },
    { id: 'tin_can', label: 'Tin Can' },
    { id: 'wooden_crates', label: 'Wooden Crates' },
    { id: 'woven_sack', label: 'Woven Sack' },
    { id: 'woven_sacks', label: 'Woven Sacks' },
  ],
  stationery: [
    { id: 'a4_size_paper', label: 'A4 Size Paper' },
    { id: 'accession_register', label: 'Accession Register' },
    { id: 'acrylic_magazine_holder', label: 'Acrylic Magazine Holder' },
    { id: 'belt', label: 'Belt' },
    { id: 'blackboard', label: 'Blackboard' },
    { id: 'business_stationery', label: 'Business Stationery' },
    { id: 'calculator_cases', label: 'Calculator Cases' },
    { id: 'calendar_hanger', label: 'Calendar Hanger' },
    { id: 'caps_hats', label: 'Caps/Hats' },
    { id: 'carbon_paper', label: 'Carbon Paper' },
    { id: 'chalk', label: 'Chalk' },
    { id: 'clip_board', label: 'Clip Board' },
    { id: 'clip_boxes', label: 'Clip Boxes' },
    { id: 'clipboard_clips', label: 'Clipboard Clips' },
    { id: 'color_opc_drum', label: 'Color Opc Drum' },
    { id: 'computer_forms', label: 'Computer Forms' },
    { id: 'computer_paper', label: 'Computer Paper' },
    { id: 'computer_stationery', label: 'Computer Stationery' },
    { id: 'conference_kits', label: 'Conference Kits' },
    { id: 'correction_fluid', label: 'Correction Fluid' },
    { id: 'desktop_calendar_stand', label: 'Desktop Calendar Stand' },
    { id: 'document_tray', label: 'Document Tray' },
    { id: 'dot_matrix_paper', label: 'Dot Matrix Paper' },
    { id: 'drawing_pins', label: 'Drawing Pins' },
    { id: 'file_dividers', label: 'File Dividers' },
    { id: 'gel_pen_set', label: 'Gel Pen Set' },
    { id: 'gloves', label: 'Gloves' },
    { id: 'hair_clips', label: 'Hair Clips' },
    { id: 'hairbands', label: 'Hairbands' },
    { id: 'handkerchief', label: 'Handkerchief' },
    {
      id: 'handmade_paper_stationery',
      label: 'Handmade Paper Stationery',
    },
    { id: 'heavy_duty_hand_stamp', label: 'Heavy Duty Hand Stamp' },
    { id: 'helmets', label: 'Helmets' },
    { id: 'hole_punches', label: 'Hole Punches' },
    { id: 'ink_pad', label: 'Ink Pad' },
    { id: 'kraft_envelope', label: 'Kraft Envelope' },
    { id: 'laptop_skin', label: 'Laptop Skin' },
    { id: 'laser_printer_parts', label: 'Laser Printer Parts' },
    {
      id: 'leather_stationery_holder',
      label: 'Leather Stationery Holder',
    },
    { id: 'leather_tumbler', label: 'Leather Tumbler' },
    { id: 'ledger_books', label: 'Ledger Books' },
    { id: 'letter_opener', label: 'Letter Opener' },
    { id: 'magazine_rack', label: 'Magazine Rack' },
    { id: 'maps', label: 'Maps' },
    { id: 'memo_book', label: 'Memo Book' },
    { id: 'memo_boxes', label: 'Memo Boxes' },
    { id: 'mouse_pads', label: 'Mouse Pads' },
    { id: 'notebook', label: 'Notebook' },
    { id: 'office_scissors', label: 'Office Scissors' },
    { id: 'office_stationery', label: 'Office Stationery' },
    { id: 'office_stationery_tray', label: 'Office Stationery Tray' },
    { id: 'pp_clipboard', label: 'Pp Clipboard' },
    { id: 'pvc_stationery_items', label: 'Pvc Stationery Items' },
    { id: 'paper_clamp', label: 'Paper Clamp' },
    { id: 'paper_cutters', label: 'Paper Cutters' },
    { id: 'paper_diaries', label: 'Paper Diaries' },
    { id: 'paper_knives', label: 'Paper Knives' },
    { id: 'paper_pins', label: 'Paper Pins' },
    { id: 'paper_punches', label: 'Paper Punches' },
    { id: 'paper_stationery', label: 'Paper Stationery' },
    { id: 'paper_tray', label: 'Paper Tray' },
    { id: 'paper_trimmer', label: 'Paper Trimmer' },
    { id: 'pen_accessories', label: 'Pen Accessories' },
    { id: 'pen_drive', label: 'Pen Drive' },
    { id: 'pen_gift_boxes', label: 'Pen Gift Boxes' },
    { id: 'pencil_bag', label: 'Pencil Bag' },
    { id: 'pencil_cups', label: 'Pencil Cups' },
    { id: 'pens', label: 'Pens' },
    { id: 'plastic_clip_board', label: 'Plastic Clip Board' },
    { id: 'printed_paper', label: 'Printed Paper' },
    { id: 'printer_consumables', label: 'Printer Consumables' },
    { id: 'printer_label', label: 'Printer Label' },
    { id: 'printer_refill', label: 'Printer Refill' },
    { id: 'printing_aids', label: 'Printing Aids' },
    { id: 'printing_ink_oil', label: 'Printing Ink Oil' },
    { id: 'promotional_items', label: 'Promotional Items' },
    {
      id: 'promotional_stationery_product',
      label: 'Promotional Stationery Products',
    },
    { id: 'push_pins', label: 'Push Pins' },
    { id: 'refill_kits', label: 'Refill Kits' },
    { id: 'ribbon_mask', label: 'Ribbon Mask' },
    { id: 'round_rubber_stamp', label: 'Round Rubber Stamp' },
    { id: 'ss_magazine_holder', label: 'Ss Magazine Holder' },
    { id: 'self_adhesive_note', label: 'Self Adhesive Note' },
    { id: 'sheet_feeders', label: 'Sheet Feeders' },
    { id: 'silicone_pads', label: 'Silicone Pads' },
    { id: 'socks_tights', label: 'Socks/Tights' },
    { id: 'staple_removers', label: 'Staple Removers' },
    { id: 'stationery_sets', label: 'Stationery Sets' },
    { id: 'steel_hand_stamp', label: 'Steel Hand Stamp' },
    { id: 'stencil', label: 'Stencil' },
    { id: 'table_tent_cards', label: 'Table Tent Cards' },
    { id: 'tent_card', label: 'Tent Card' },
    { id: 'thermal_print_heads', label: 'Thermal Print-heads' },
    { id: 'transfer_papers', label: 'Transfer Papers' },
    { id: 'visitor_register', label: 'Visitor Register' },
    { id: 'wooden_bookends', label: 'Wooden Bookends' },
    { id: 'wooden_clipboard', label: 'Wooden Clipboard' },
    { id: 'wooden_magazine_holder', label: 'Wooden Magazine Holder' },
    { id: 'wooden_pen_set', label: 'Wooden Pen Set' },
    { id: 'wooden_visiting_card_box', label: 'Wooden Visiting Card Box' },
    { id: 'writing_board', label: 'Writing Board' },
    { id: 'writing_pad', label: 'Writing Pad' },
    { id: 'writing_paper', label: 'Writing Paper' },
    { id: 'writing_set', label: 'Writing Set' },
  ],
  threads_and_laces: [
    { id: 'chenille', label: 'Chenille' },
    { id: 'corset', label: 'Corset' },
    { id: 'cotton', label: 'Cotton' },
    { id: 'crosia', label: 'Crosia' },
    { id: 'georgette', label: 'Georgette' },
    { id: 'gota', label: 'Gota' },
    { id: 'hand_embroidered', label: 'Hand Embroidered' },
    { id: 'jute', label: 'Jute' },
    { id: 'lycra', label: 'Lycra' },
    { id: 'name', label: 'Name' },
    { id: 'nylon', label: 'Nylon' },
    { id: 'polyester', label: 'Polyester' },
    { id: 'rayon', label: 'Rayon' },
    { id: 'ric_rac', label: 'Ric Rac' },
    { id: 'saree_lace', label: 'Saree Lace' },
    { id: 'silk_lace', label: 'Silk Lace' },
    { id: 'velvet_tape', label: 'Velvet Tape' },
    { id: 'zari', label: 'Zari' },
  ],
  toys: [
    { id: 'activity', label: 'Activity' },
    { id: 'archery', label: 'Archery' },
    { id: 'badminton', label: 'Badminton' },
    { id: 'ball', label: 'Ball' },
    { id: 'beach_toys', label: 'Beach Toys' },
    { id: 'beyblade', label: 'Beyblade' },
    { id: 'billiards', label: 'Billiards' },
    { id: 'business', label: 'Business' },
    { id: 'cards', label: 'Cards' },
    { id: 'carrom', label: 'Carrom' },
    { id: 'chess', label: 'Chess' },
    { id: 'cricket', label: 'Cricket' },
    { id: 'dolls', label: 'Dolls' },
    { id: 'educational', label: 'Educational' },
    { id: 'fruit_toys', label: 'Fruit Toys' },
    { id: 'hockey', label: 'Hockey' },
    { id: 'ludo', label: 'Ludo' },
    { id: 'musical', label: 'Musical' },
    { id: 'puzzles', label: 'Puzzles' },
    { id: 'ride_on', label: 'Ride-On' },
    { id: 'shooting', label: 'Shooting' },
    { id: 'shuttle_cock', label: 'Shuttle Cock' },
    { id: 'snakes_ladders', label: 'Snakes & Ladders' },
    { id: 'soft_toys', label: 'Soft Toys' },
    { id: 'table_tennis', label: 'Table Tennis' },
    { id: 'tennis', label: 'Tennis' },
  ],
  cleaners: [],
  electric_vehicle: [],
  electrical: [],
  handmade_emporium: [],
  plastic_ware: [],
  sports: [],
  textile_fabrics: [],
};

export const SubMenuOptions: {
  [k in MenuCategoriesIdType]: SelectItemElement[];
} = Object.entries(SubCategories).reduce(
  (a, [k, v]) => ({
    ...a,
    [k]: v.map((sc) => ({ id: sc.id, item: sc.label })),
  }),
  {} as Record<MenuCategoriesIdType, SelectItemElement[]>,
);
