import './global.css';
import styles from './base.module.css';
import { MenuBar, NavHeader, PageFooter } from '@md/blaunk/pages/layout';

export const metadata = {
  title: 'Welcome to Blaunk',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>Blaunk</title>
      <body>
        <div className={styles.root}>
          <div className={styles.background}>
            <div className={styles.layout}>
              <NavHeader />
              <div className={`${styles.content} ${styles.scrollbar}`}>
                <MenuBar />
                <div className={styles.pages}>{children}</div>
                <PageFooter />
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
