import clsx from 'clsx';
import './global.css';
import styles from './base.module.css';
import blaunkStyles from './blaunk.module.css';
import { NavHeader, PageFooter } from '@md/blaunk/pages/layout';
import { rs, sbs } from '@li/config/design';
import { ReactChildren } from '@li/types/shared';

export const metadata = {
  title: 'Blaunk',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: ReactChildren) {
  return (
    <html lang="en" className={clsx(rs.root, blaunkStyles.base)}>
      <body className={blaunkStyles.base}>
        <div className={styles.root}>
          <div className={styles.background}>
            <div className={styles.layout}>
              <NavHeader />
              <div className={`${styles.content} ${sbs.dark}`}>
                {children}
                <PageFooter />
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
