import {
  Bahrain,
  Bangladesh,
  Bhutan,
  India,
  Indonesia,
  Jordan,
  Malaysia,
  Maldives,
  Nepal,
  Philippines,
  Singapore,
  SouthAfrica,
  SriLanka,
  Thailand,
  UnitedArabEmirates,
  Vietnam,
} from '@li/design/icons';
import type {
  CountryCode,
  CountryFlag as CF,
  CountryName as CN,
  CountryPhoneCode as CPC,
} from '@li/types/config';

export const CountryName: { [k in CountryCode]: CN } = {
  ad: 'Andorra',
  // ae: 'United Arab Emirates',
  ae: 'UAE',
  af: 'Afghanistan',
  ag: 'Antigua & Barbuda',
  al: 'Albania',
  am: 'Armenia',
  ao: 'Angola',
  ar: 'Argentina',
  at: 'Austria',
  au: 'Australia',
  az: 'Azerbaijan',
  ba: 'Bosnia and Herzegovina',
  bb: 'Barbados',
  bd: 'Bangladesh',
  be: 'Belgium',
  bf: 'Burkina Faso',
  bg: 'Bulgaria',
  bh: 'Bahrain',
  bi: 'Burundi',
  bj: 'Benin',
  bm: 'Bermuda',
  bn: 'Brunei',
  bo: 'Bolivia',
  br: 'Brazil',
  bs: 'Bahamas',
  bt: 'Bhutan',
  bw: 'Botswana',
  by: 'Belarus',
  bz: 'Belize',
  ca: 'Canada',
  cd: 'Congo Democratic Republic',
  cf: 'Central African Republic',
  cg: 'Congo',
  ch: 'Switzerland',
  ci: "Cote d'Ivoire",
  cl: 'Chile',
  cm: 'Cameroon',
  cn: 'China',
  co: 'Colombia',
  cr: 'Costa Rica',
  cu: 'Cuba',
  cv: 'Cape Verde',
  cy: 'Cyprus',
  cz: 'Czech Republic',
  de: 'Germany',
  dj: 'Djibouti',
  dk: 'Denmark',
  dm: 'Dominica',
  do: 'Dominican Republic',
  dz: 'Algeria',
  ec: 'Ecuador',
  ee: 'Estonia',
  eg: 'Egypt',
  er: 'Eritrea',
  es: 'Spain',
  et: 'Ethiopia',
  fi: 'Finland',
  fj: 'Fiji',
  fm: 'Micronesia',
  fr: 'France',
  ga: 'Gabon',
  gb: 'Great Britain',
  gd: 'Grenada',
  ge: 'Georgia',
  gh: 'Ghana',
  gm: 'Gambia',
  gn: 'Guinea',
  gq: 'Equatorial Guinea',
  gr: 'Greece',
  gt: 'Guatemala',
  gw: 'Guinea-Bissau',
  gy: 'Guyana',
  hk: 'Hong Kong',
  hn: 'Honduras',
  hr: 'Croatia',
  ht: 'Haiti',
  hu: 'Hungary',
  id: 'Indonesia',
  ie: 'Ireland',
  il: 'Israel',
  in: 'India',
  iq: 'Iraq',
  ir: 'Iran',
  is: 'Iceland',
  it: 'Italy',
  jm: 'Jamaica',
  jo: 'Jordan',
  jp: 'Japan',
  ke: 'Kenya',
  kg: 'Kyrgyzstan',
  kh: 'Cambodia',
  ki: 'Kiribati',
  km: 'Comoros',
  kn: 'St. Kitts & Nevis',
  kp: 'Korea North',
  kr: 'South Korea',
  ks: 'Kosovo',
  kw: 'Kuwait',
  kz: 'Kazakhstan',
  la: 'Laos',
  lb: 'Lebanon',
  lc: 'St. Lucia',
  li: 'Liechtenstein',
  lk: 'Sri Lanka',
  lr: 'Liberia',
  ls: 'Lesotho',
  lt: 'Lithuania',
  lu: 'Luxembourg',
  lv: 'Latvia',
  ly: 'Libya',
  ma: 'Morocco',
  mc: 'Monaco',
  md: 'Moldova',
  me: 'Montenegro',
  mg: 'Madagascar',
  mh: 'Marshall Islands',
  mk: 'North Macedonia',
  ml: 'Mali',
  mm: 'Myanmar (Burma)',
  mn: 'Mongolia',
  mo: 'Macao',
  mr: 'Mauritania',
  mt: 'Malta',
  mu: 'Mauritius',
  mv: 'Maldives',
  mw: 'Malawi',
  mx: 'Mexico',
  my: 'Malaysia',
  mz: 'Mozambique',
  na: 'Namibia',
  ne: 'Niger',
  ng: 'Nigeria',
  ni: 'Nicaragua',
  nl: 'Netherlands',
  no: 'Norway',
  np: 'Nepal',
  nr: 'Nauru',
  nz: 'New Zealand',
  om: 'Oman',
  pa: 'Panama',
  pe: 'Peru',
  pf: 'French Polynesia',
  pg: 'Papua New Guinea',
  ph: 'Philippines',
  pk: 'Pakistan',
  pl: 'Poland',
  pt: 'Portugal',
  pw: 'Palau',
  py: 'Paraguay',
  qa: 'Qatar',
  ro: 'Romania',
  rs: 'Serbia',
  ru: 'Russia',
  rw: 'Rwanda',
  sa: 'Saudi Arabia',
  sb: 'Solomon Islands',
  sc: 'Seychelles',
  sd: 'South Sudan',
  se: 'Sweden',
  sg: 'Singapore',
  si: 'Slovenia',
  sk: 'Slovakia',
  sl: 'Sierra Leone',
  sm: 'San Marino',
  sn: 'Senegal',
  so: 'Somalia',
  sr: 'Suriname',
  st: 'Sao Tome & Principe',
  sv: 'El Salvador',
  sy: 'Syria',
  sz: 'Swaziland',
  td: 'Chad',
  tg: 'Togo',
  th: 'Thailand',
  tj: 'Tajikistan',
  tm: 'Turkmenistan',
  tn: 'Tunisia',
  to: 'Tonga',
  tr: 'Turkey',
  tt: 'Trinidad & Tobago',
  tv: 'Tuvalu',
  tw: 'Taiwan',
  tz: 'Tanzania',
  ua: 'Ukraine',
  ug: 'Uganda',
  us: 'United States of America',
  uy: 'Uruguay',
  uz: 'Uzbekistan',
  va: 'Vatican City (Holy See)',
  vc: 'St. Vincent & The Grenadines',
  ve: 'Venezuela',
  vn: 'Vietnam',
  vu: 'Vanuatu',
  ws: 'Samoa',
  ye: 'Yemen',
  za: 'South Africa',
  zm: 'Zambia',
  zw: 'Zimbabwe',
};

export const CountryPhoneCode: { [k in CountryCode]: CPC } = {
  ad: '+376',
  ae: '+971',
  af: '+93',
  ag: '+1',
  al: '+355',
  am: '+374',
  ao: '+244',
  ar: '+54',
  at: '+43',
  au: '+61',
  az: '+994',
  ba: '+387',
  bb: '+1246',
  bd: '+880',
  be: '+32',
  bf: '+226',
  bg: '+359',
  bh: '+973',
  bi: '+257',
  bj: '+229',
  bm: '+441',
  bn: '+673',
  bo: '+591',
  br: '+55',
  bs: '+1242',
  bt: '+975',
  bw: '+267',
  by: '+375',
  bz: '+501',
  ca: '+1',
  cd: '+243',
  cf: '+236',
  cg: '+242',
  ch: '+41',
  ci: '+225',
  cl: '+56',
  cm: '+237',
  cn: '+86',
  co: '+57',
  cr: '+506',
  cu: '+53',
  cv: '+238',
  cy: '+357',
  cz: '+420',
  de: '+49',
  dj: '+253',
  dk: '+45',
  dm: '+1767',
  do: '+1809',
  dz: '+213',
  ec: '+593',
  ee: '+372',
  eg: '+20',
  er: '+291',
  es: '+34',
  et: '+251',
  fi: '+358',
  fj: '+679',
  fm: '+691',
  fr: '+33',
  ga: '+241',
  gb: '+44',
  gd: '+1473',
  ge: '+995',
  gh: '+233',
  gm: '+220',
  gn: '+224',
  gq: '+240',
  gr: '+30',
  gt: '+502',
  gw: '+245',
  gy: '+592',
  hk: '+852',
  hn: '+504',
  hr: '+385',
  ht: '+509',
  hu: '+36',
  id: '+62',
  ie: '+353',
  il: '+972',
  in: '+91',
  iq: '+964',
  ir: '+98',
  is: '+354',
  it: '+39',
  jm: '+1876',
  jo: '+962',
  jp: '+81',
  ke: '+254',
  kg: '+996',
  kh: '+855',
  ki: '+686',
  km: '+269',
  kn: '+1',
  kp: '+850',
  kr: '+82',
  ks: '+383',
  kw: '+965',
  kz: '+76,77',
  la: '+856',
  lb: '+961',
  lc: '+1',
  li: '+423',
  lk: '+94',
  lr: '+231',
  ls: '+266',
  lt: '+370',
  lu: '+352',
  lv: '+371',
  ly: '+218',
  ma: '+212',
  mc: '+377',
  md: '+373',
  me: '+382',
  mg: '+261',
  mh: '+692',
  mk: '+389',
  ml: '+223',
  mm: '+95',
  mn: '+976',
  mo: '+853',
  mr: '+222',
  mt: '+356',
  mu: '+230',
  mv: '+960',
  mw: '+265',
  mx: '+52',
  my: '+60',
  mz: '+258',
  na: '+264',
  ne: '+227',
  ng: '+234',
  ni: '+505',
  nl: '+31',
  no: '+47',
  np: '+977',
  nr: '+674',
  nz: '+64',
  om: '+968',
  pa: '+507',
  pe: '+51',
  pf: '+689',
  pg: '+675',
  ph: '+63',
  pk: '+92',
  pl: '+48',
  pt: '+351',
  pw: '+680',
  py: '+595',
  qa: '+974',
  ro: '+40',
  rs: '+381',
  ru: '+7',
  rw: '+250',
  sa: '+966',
  sb: '+677',
  sc: '+248',
  sd: '+211',
  se: '+46',
  sg: '+65',
  si: '+386',
  sk: '+421',
  sl: '+232',
  sm: '+378',
  sn: '+221',
  so: '+252',
  sr: '+597',
  st: '+239',
  sv: '+503',
  sy: '+963',
  sz: '+268',
  td: '+235',
  tg: '+228',
  th: '+66',
  tj: '+992',
  tm: '+993',
  tn: '+216',
  to: '+676',
  tr: '+90',
  tt: '+868',
  tv: '+688',
  tw: '+886',
  tz: '+255',
  ua: '+380',
  ug: '+256',
  us: '+1',
  uy: '+598',
  uz: '+998',
  va: '+379',
  vc: '+1',
  ve: '+58',
  vn: '+84',
  vu: '+678',
  ws: '+685',
  ye: '+967',
  za: '+27',
  zm: '+260',
  zw: '+263',
};

export const CountryFlag: { [k in CountryCode]: CF | undefined } = {
  ad: undefined,
  ae: {
    Flag: <UnitedArabEmirates />,
    color: 'red',
    colorOnColor: '#fff',
  },
  af: undefined,
  ag: undefined,
  al: undefined,
  am: undefined,
  ao: undefined,
  ar: undefined,
  at: undefined,
  au: undefined,
  az: undefined,
  ba: undefined,
  bb: undefined,
  bd: {
    Flag: <Bangladesh />,
    color: '#006A4E',
    colorOnColor: '#F42A41',
  },
  be: undefined,
  bf: undefined,
  bg: undefined,
  bh: {
    Flag: <Bahrain />,
    color: '#CE1126',
    colorOnColor: '#fff',
  },
  bi: undefined,
  bj: undefined,
  bm: undefined,
  bn: undefined,
  bo: undefined,
  br: undefined,
  bs: undefined,
  bt: {
    Flag: <Bhutan />,
    color: '#FF4E12',
    colorOnColor: '#fff',
  },
  bw: undefined,
  by: undefined,
  bz: undefined,
  ca: undefined,
  cd: undefined,
  cf: undefined,
  cg: undefined,
  ch: undefined,
  ci: undefined,
  cl: undefined,
  cm: undefined,
  cn: undefined,
  co: undefined,
  cr: undefined,
  cu: undefined,
  cv: undefined,
  cy: undefined,
  cz: undefined,
  de: undefined,
  dj: undefined,
  dk: undefined,
  dm: undefined,
  do: undefined,
  dz: undefined,
  ec: undefined,
  ee: undefined,
  eg: undefined,
  er: undefined,
  es: undefined,
  et: undefined,
  fi: undefined,
  fj: undefined,
  fm: undefined,
  fr: undefined,
  ga: undefined,
  gb: undefined,
  gd: undefined,
  ge: undefined,
  gh: undefined,
  gm: undefined,
  gn: undefined,
  gq: undefined,
  gr: undefined,
  gt: undefined,
  gw: undefined,
  gy: undefined,
  hk: undefined,
  hn: undefined,
  hr: undefined,
  ht: undefined,
  hu: undefined,
  id: {
    Flag: <Indonesia />,
    color: '#E70011',
    colorOnColor: '#fff',
  },
  ie: undefined,
  il: undefined,
  in: {
    Flag: <India />,
    color: '#F93',
    colorOnColor: '#008',
  },
  iq: undefined,
  ir: undefined,
  is: undefined,
  it: undefined,
  jm: undefined,
  jo: {
    Flag: <Jordan />,
    color: '#ce1126',
    colorOnColor: '#fff',
  },
  jp: undefined,
  ke: undefined,
  kg: undefined,
  kh: undefined,
  ki: undefined,
  km: undefined,
  kn: undefined,
  kp: undefined,
  kr: undefined,
  ks: undefined,
  kw: undefined,
  kz: undefined,
  la: undefined,
  lb: undefined,
  lc: undefined,
  li: undefined,
  lk: {
    Flag: <SriLanka />,
    color: '#8D2029',
    colorOnColor: '#FFB700',
  },
  lr: undefined,
  ls: undefined,
  lt: undefined,
  lu: undefined,
  lv: undefined,
  ly: undefined,
  ma: undefined,
  mc: undefined,
  md: undefined,
  me: undefined,
  mg: undefined,
  mh: undefined,
  mk: undefined,
  ml: undefined,
  mm: undefined,
  mn: undefined,
  mo: undefined,
  mr: undefined,
  mt: undefined,
  mu: undefined,
  mv: {
    Flag: <Maldives />,
    color: '#007E3A',
    colorOnColor: '#fff',
  },
  mw: undefined,
  mx: undefined,
  my: {
    Flag: <Malaysia />,
    color: '#006',
    colorOnColor: '#FC0',
  },
  mz: undefined,
  na: undefined,
  ne: undefined,
  ng: undefined,
  ni: undefined,
  nl: undefined,
  no: undefined,
  np: {
    Flag: <Nepal />,
    color: '#CE0000',
    colorOnColor: '#fff',
  },
  nr: undefined,
  nz: undefined,
  om: undefined,
  pa: undefined,
  pe: undefined,
  pf: undefined,
  pg: undefined,
  ph: {
    Flag: <Philippines />,
    color: '#fff',
    colorOnColor: '#FCD116',
  },
  pk: undefined,
  pl: undefined,
  pt: undefined,
  pw: undefined,
  py: undefined,
  qa: undefined,
  ro: undefined,
  rs: undefined,
  ru: undefined,
  rw: undefined,
  sa: undefined,
  sb: undefined,
  sc: undefined,
  sd: undefined,
  se: undefined,
  sg: {
    Flag: <Singapore />,
    color: '#DF0000',
    colorOnColor: '#fff',
  },
  si: undefined,
  sk: undefined,
  sl: undefined,
  sm: undefined,
  sn: undefined,
  so: undefined,
  sr: undefined,
  st: undefined,
  sv: undefined,
  sy: undefined,
  sz: undefined,
  td: undefined,
  tg: undefined,
  th: {
    Flag: <Thailand />,
    color: '#A51931',
    colorOnColor: '#F4F5F8',
  },
  tj: undefined,
  tm: undefined,
  tn: undefined,
  to: undefined,
  tr: undefined,
  tt: undefined,
  tv: undefined,
  tw: undefined,
  tz: undefined,
  ua: undefined,
  ug: undefined,
  us: undefined,
  uy: undefined,
  uz: undefined,
  va: undefined,
  vc: undefined,
  ve: undefined,
  vn: {
    Flag: <Vietnam />,
    color: '#DA251D',
    colorOnColor: '#FF0',
  },
  vu: undefined,
  ws: undefined,
  ye: undefined,
  za: {
    Flag: <SouthAfrica />,
    color: '#FFB915',
    colorOnColor: '#000',
  },
  zm: undefined,
  zw: undefined,
};
