import {
  Bahrain,
  Bangladesh,
  Bhutan,
  India,
  Jordan,
  Maldives,
  Nepal,
  Philippines,
  SriLanka,
} from '@li/design/icons';
import { CountryCode, CountryFlag, CountryName } from '@li/types/config';

export const CountryNames: { [k in CountryCode]: CountryName } = {
  ad: 'Andorra',
  ae: 'United Arab Emirates',
  af: 'Afghanistan',
  ag: 'Antigua & Barbuda',
  al: 'Albania',
  am: 'Armenia',
  ao: 'Angola',
  ar: 'Argentina',
  at: 'Austria',
  au: 'Australia',
  az: 'Azerbaijan',
  ba: 'Bosnia and Herzegovina',
  bb: 'Barbados',
  bd: 'Bangladesh',
  be: 'Belgium',
  bf: 'Burkina Faso',
  bg: 'Bulgaria',
  bh: 'Bahrain',
  bi: 'Burundi',
  bj: 'Benin',
  bm: 'Bermuda',
  bn: 'Brunei',
  bo: 'Bolivia',
  br: 'Brazil',
  bs: 'Bahamas',
  bt: 'Bhutan',
  bw: 'Botswana',
  by: 'Belarus',
  bz: 'Belize',
  ca: 'Canada',
  cd: 'Congo Democratic Republic',
  cf: 'Central African Republic',
  cg: 'Congo',
  ch: 'Switzerland',
  ci: "Cote d'Ivoire",
  cl: 'Chile',
  cm: 'Cameroon',
  cn: 'China',
  co: 'Colombia',
  cr: 'Costa Rica',
  cu: 'Cuba',
  cv: 'Cape Verde',
  cy: 'Cyprus',
  cz: 'Czech Republic',
  de: 'Germany',
  dj: 'Djibouti',
  dk: 'Denmark',
  dm: 'Dominica',
  do: 'Dominican Republic',
  dz: 'Algeria',
  ec: 'Ecuador',
  ee: 'Estonia',
  eg: 'Egypt',
  er: 'Eritrea',
  es: 'Spain',
  et: 'Ethiopia',
  fi: 'Finland',
  fj: 'Fiji',
  fm: 'Micronesia',
  fr: 'France',
  ga: 'Gabon',
  gb: 'Great Britain',
  gd: 'Grenada',
  ge: 'Georgia',
  gh: 'Ghana',
  gm: 'Gambia',
  gn: 'Guinea',
  gq: 'Equatorial Guinea',
  gr: 'Greece',
  gt: 'Guatemala',
  gw: 'Guinea-Bissau',
  gy: 'Guyana',
  hk: 'Hong Kong',
  hn: 'Honduras',
  hr: 'Croatia',
  ht: 'Haiti',
  hu: 'Hungary',
  id: 'Indonesia',
  ie: 'Ireland',
  il: 'Israel',
  in: 'India',
  iq: 'Iraq',
  ir: 'Iran',
  is: 'Iceland',
  it: 'Italy',
  jm: 'Jamaica',
  jo: 'Jordan',
  jp: 'Japan',
  ke: 'Kenya',
  kg: 'Kyrgyzstan',
  kh: 'Cambodia',
  ki: 'Kiribati',
  km: 'Comoros',
  kn: 'St. Kitts & Nevis',
  kp: 'Korea North',
  kr: 'South Korea',
  ks: 'Kosovo',
  kw: 'Kuwait',
  kz: 'Kazakhstan',
  la: 'Laos',
  lb: 'Lebanon',
  lc: 'St. Lucia',
  li: 'Liechtenstein',
  lk: 'Sri Lanka',
  lr: 'Liberia',
  ls: 'Lesotho',
  lt: 'Lithuania',
  lu: 'Luxembourg',
  lv: 'Latvia',
  ly: 'Libya',
  ma: 'Morocco',
  mc: 'Monaco',
  md: 'Moldova',
  me: 'Montenegro',
  mg: 'Madagascar',
  mh: 'Marshall Islands',
  mk: 'North Macedonia',
  ml: 'Mali',
  mm: 'Myanmar (Burma)',
  mn: 'Mongolia',
  mo: 'Macao',
  mr: 'Mauritania',
  mt: 'Malta',
  mu: 'Mauritius',
  mv: 'Maldives',
  mw: 'Malawi',
  mx: 'Mexico',
  my: 'Malaysia',
  mz: 'Mozambique',
  na: 'Namibia',
  ne: 'Niger',
  ng: 'Nigeria',
  ni: 'Nicaragua',
  nl: 'Netherlands',
  no: 'Norway',
  np: 'Nepal',
  nr: 'Nauru',
  nz: 'New Zealand',
  om: 'Oman',
  pa: 'Panama',
  pe: 'Peru',
  pf: 'French Polynesia',
  pg: 'Papua New Guinea',
  ph: 'Philippines',
  pk: 'Pakistan',
  pl: 'Poland',
  pt: 'Portugal',
  pw: 'Palau',
  py: 'Paraguay',
  qa: 'Qatar',
  ro: 'Romania',
  rs: 'Serbia',
  ru: 'Russia',
  rw: 'Rwanda',
  sa: 'Saudi Arabia',
  sb: 'Solomon Islands',
  sc: 'Seychelles',
  sd: 'South Sudan',
  se: 'Sweden',
  sg: 'Singapore',
  si: 'Slovenia',
  sk: 'Slovakia',
  sl: 'Sierra Leone',
  sm: 'San Marino',
  sn: 'Senegal',
  so: 'Somalia',
  sr: 'Suriname',
  st: 'Sao Tome & Principe',
  sv: 'El Salvador',
  sy: 'Syria',
  sz: 'Swaziland',
  td: 'Chad',
  tg: 'Togo',
  th: 'Thailand',
  tj: 'Tajikistan',
  tm: 'Turkmenistan',
  tn: 'Tunisia',
  to: 'Tonga',
  tr: 'Turkey',
  tt: 'Trinidad & Tobago',
  tv: 'Tuvalu',
  tw: 'Taiwan',
  tz: 'Tanzania',
  ua: 'Ukraine',
  ug: 'Uganda',
  us: 'United States of America',
  uy: 'Uruguay',
  uz: 'Uzbekistan',
  va: 'Vatican City (Holy See)',
  vc: 'St. Vincent & The Grenadines',
  ve: 'Venezuela',
  vn: 'Vietnam',
  vu: 'Vanuatu',
  ws: 'Samoa',
  ye: 'Yemen',
  za: 'South Africa',
  zm: 'Zambia',
  zw: 'Zimbabwe',
};

export const CountryFlags: { [k in CountryCode]: CountryFlag | undefined } = {
  ad: undefined,
  ae: undefined,
  af: undefined,
  ag: undefined,
  al: undefined,
  am: undefined,
  ao: undefined,
  ar: undefined,
  at: undefined,
  au: undefined,
  az: undefined,
  ba: undefined,
  bb: undefined,
  bd: {
    Flag: Bangladesh,
    color: '#006A4E',
    colorOnColor: '#F42A41',
  },
  be: undefined,
  bf: undefined,
  bg: undefined,
  bh: {
    Flag: Bahrain,
    color: '#CE1126',
    colorOnColor: '#fff',
  },
  bi: undefined,
  bj: undefined,
  bm: undefined,
  bn: undefined,
  bo: undefined,
  br: undefined,
  bs: undefined,
  bt: {
    Flag: Bhutan,
    color: '#FF4E12',
    colorOnColor: '#fff',
  },
  bw: undefined,
  by: undefined,
  bz: undefined,
  ca: undefined,
  cd: undefined,
  cf: undefined,
  cg: undefined,
  ch: undefined,
  ci: undefined,
  cl: undefined,
  cm: undefined,
  cn: undefined,
  co: undefined,
  cr: undefined,
  cu: undefined,
  cv: undefined,
  cy: undefined,
  cz: undefined,
  de: undefined,
  dj: undefined,
  dk: undefined,
  dm: undefined,
  do: undefined,
  dz: undefined,
  ec: undefined,
  ee: undefined,
  eg: undefined,
  er: undefined,
  es: undefined,
  et: undefined,
  fi: undefined,
  fj: undefined,
  fm: undefined,
  fr: undefined,
  ga: undefined,
  gb: undefined,
  gd: undefined,
  ge: undefined,
  gh: undefined,
  gm: undefined,
  gn: undefined,
  gq: undefined,
  gr: undefined,
  gt: undefined,
  gw: undefined,
  gy: undefined,
  hk: undefined,
  hn: undefined,
  hr: undefined,
  ht: undefined,
  hu: undefined,
  id: undefined,
  ie: undefined,
  il: undefined,
  in: {
    Flag: India,
    color: '#F93',
    colorOnColor: '#008',
  },
  iq: undefined,
  ir: undefined,
  is: undefined,
  it: undefined,
  jm: undefined,
  jo: {
    Flag: Jordan,
    color: '#ce1126',
    colorOnColor: '#fff',
  },
  jp: undefined,
  ke: undefined,
  kg: undefined,
  kh: undefined,
  ki: undefined,
  km: undefined,
  kn: undefined,
  kp: undefined,
  kr: undefined,
  ks: undefined,
  kw: undefined,
  kz: undefined,
  la: undefined,
  lb: undefined,
  lc: undefined,
  li: undefined,
  lk: {
    Flag: SriLanka,
    color: '#8D2029',
    colorOnColor: '#FFB700',
  },
  lr: undefined,
  ls: undefined,
  lt: undefined,
  lu: undefined,
  lv: undefined,
  ly: undefined,
  ma: undefined,
  mc: undefined,
  md: undefined,
  me: undefined,
  mg: undefined,
  mh: undefined,
  mk: undefined,
  ml: undefined,
  mm: undefined,
  mn: undefined,
  mo: undefined,
  mr: undefined,
  mt: undefined,
  mu: undefined,
  mv: {
    Flag: Maldives,
    color: '#007E3A',
    colorOnColor: '#fff',
  },
  mw: undefined,
  mx: undefined,
  my: undefined,
  mz: undefined,
  na: undefined,
  ne: undefined,
  ng: undefined,
  ni: undefined,
  nl: undefined,
  no: undefined,
  np: {
    Flag: Nepal,
    color: '#CE0000',
    colorOnColor: '#fff',
  },
  nr: undefined,
  nz: undefined,
  om: undefined,
  pa: undefined,
  pe: undefined,
  pf: undefined,
  pg: undefined,
  ph: {
    Flag: Philippines,
    color: '#fff',
    colorOnColor: '#FCD116',
  },
  pk: undefined,
  pl: undefined,
  pt: undefined,
  pw: undefined,
  py: undefined,
  qa: undefined,
  ro: undefined,
  rs: undefined,
  ru: undefined,
  rw: undefined,
  sa: undefined,
  sb: undefined,
  sc: undefined,
  sd: undefined,
  se: undefined,
  sg: undefined,
  si: undefined,
  sk: undefined,
  sl: undefined,
  sm: undefined,
  sn: undefined,
  so: undefined,
  sr: undefined,
  st: undefined,
  sv: undefined,
  sy: undefined,
  sz: undefined,
  td: undefined,
  tg: undefined,
  th: undefined,
  tj: undefined,
  tm: undefined,
  tn: undefined,
  to: undefined,
  tr: undefined,
  tt: undefined,
  tv: undefined,
  tw: undefined,
  tz: undefined,
  ua: undefined,
  ug: undefined,
  us: undefined,
  uy: undefined,
  uz: undefined,
  va: undefined,
  vc: undefined,
  ve: undefined,
  vn: undefined,
  vu: undefined,
  ws: undefined,
  ye: undefined,
  za: undefined,
  zm: undefined,
  zw: undefined,
};
