import { ReactChildren } from '@li/types/shared';
import './global.css';

export const metadata = {
  title: 'Welcome to blaunk/admin',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: ReactChildren) {
  return (
    <html lang="en">
      <title>Admin | Blaunk</title>
      <body>
        <div className="root-div">{children}</div>
      </body>
    </html>
  );
}
