import './global.css';

export const metadata = {
  title: 'Welcome to blaunk/admin',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>Admin | Blaunk</title>
      <body>
        <div className="root-div">{children}</div>
      </body>
    </html>
  );
}
